### PR TITLE
chore(www): ui contrasts + disable lightmode

### LINKED ISSUE #432: feat: Introduction revamp
### Is your feature request related to a problem? Please describe.

https://create-t3-app-nu.vercel.app/en/introduction

The chosen text-color for the links don't mix very well with the chosen background, there needs to be way more contrast than as of now.

image
image
image

Not very readable.

### Describe the solution you'd like to see

A change in the styling of links on the documentation page.

### Desribe alternate solutions

...

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #432

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Increase contrast ratios
- Temporarily disables lightmode (https://github.com/t3-oss/create-t3-app/issues/436#issuecomment-1245926388)

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
> ⚡️ [Lighthouse report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1663101140133-86938.report.html) for the changes in this PR:
> 
> Category	Score
> 🟠 Performance	74
> 🟠 Accessibility	88
> 🟠 Best practices	86
> 🟠 SEO	70
> 🟠 PWA	54
> _Lighthouse ran on https://create-t3-app-git-julius-docs-runthrough-t3-oss.vercel.app/_

@nexxeln @kroucher @c-ehrlich I think we have some leakage somewhere 🤔

**Comment by kroucher** [comment]
> > ⚡️ [Lighthouse report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1663101140133-86938.report.html) for the changes in this PR:
> > Category	Score
> > 🟠 Performance	74
> > 🟠 Accessibility	88
> > 🟠 Best practices	86
> > 🟠 SEO	70
> > 🟠 PWA	54
> > _Lighthouse ran on https://create-t3-app-git-julius-docs-runthrough-t3-oss.vercel.app/_
> 
> @nexxeln @kroucher @c-ehrlich I think we have some leakage somewhere 🤔
> 
> EDIT: Oh wait is this cause the lambda is cold the first lighthouse run gets crappy scores?

Shouldn't be any lambda's, it's all just html being spat on a page.

I just ran a lighthouse on my PC with ^that URL (in incognito) and getting the below:
image

There's definitely some stuff to be fixed, awesome workflow task indeed.

**Comment by juliusmarminge** [comment]
Tried running it via the CLI, which is what that workflow is doing and got 

CleanShot 2022-09-13 at 23 14 15

Is there a better way to run a workflow like this 🤔

**Review by kroucher — APPROVED** [review]
All looks great on my end

**Pull request merged**
