### PR TITLE
fix(t3-app): resolve target area of `Documentation` links in `TechnologyCard`

### PR DESCRIPTION
**Pull request by EkkoKo**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

In the tailwind template if you would of hovered the link inside the `TechnologyCard`  you could of clicked the link anywhere in that line even if you weren't hovering the text, I found this very annoying and changed it by making only when you click on the text "Documentation" to redirect you to the documentation of the technology that card mentioned.
---

## Screenshots

Before you could of clicked anywhere in that line
image

Now only when you click on the link it will redirect you
image

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Thank you. Would you also mind fixing the `with-*-tw`?

**Comment by EkkoKo** [comment]
> Thank you. Would you also mind fixing the rest of the `with-*-tw`?

Yeah for sure!
Pushed all the changes now

**Comment by EkkoKo** [comment]
Also I saw there was a merging issue which I resolved now :)

**Comment by juliusmarminge** [comment]
Nice. There are some formatting issues. You may need to run `pnpm install` to make sure that the prettier plugins are installed then run `pnpm format` to make sure the code is formatted and Tailwind classes sorted properly

**Review by juliusmarminge — APPROVED** [review]
I'll fix formatting after merge

**Review by c-ehrlich — COMMENTED** [review]
Looks good to me. I don't think I have permission to merge as long as it fails CI, I'd be fine with either Julius/Nexxel merging, or merging myself if you make prettier happy.

**Comment by EkkoKo** [comment]
Hey! I've been away from my computer in the past couple of days so I didn't see the pr reply, would you like me to run the formatting and push it?

**Comment by juliusmarminge** [comment]
> Hey! I've been away from my computer in the past couple of days so I didn't see the pr reply, would you like me to run the formatting and push it?
> 

Would be great, thanks 🙏

**Comment by EkkoKo** [comment]
Alright great, I'll be on my computer in a couple of hours and push those changes

**Comment by c-ehrlich** [comment]
Thanks :)

**Pull request merged**
