### PR TITLE
docs: bug - firefox doesn't always use custom scrollbars

### LINKED ISSUE #723: bug: docs - firefox doesn't always use custom scrollbars
### Provide environment information

firefox on macos

### Describe the bug

Firefox doesn't use our custom scrollbar on the left nav in docs for some reason. Also for the main window scrollbar it uses a weird thing that looks like a hybrid between our custom scrollbar and the default macos scrollbar.

This issue remains in https://github.com/t3-oss/create-t3-app/pull/714 but I will not try to fix it there as that PR is more than big enough already

Chrome (expected behavior):
Screenshot 2022-11-12 at 13 05 40

Firefox (incorrect behavior)
Screenshot 2022-11-12 at 13 05 10

### To reproduce

Head to https://beta.create.t3.gg/en/other-recs on Firefox

### Additional information

If someone wants to work on this I would suggest to wait until after #714 is merged, to avoid having to deal with a potential mess of a merge conflict

Also would be nice if someone on Windows/Linux could tell me how it is there.

### PR DESCRIPTION
**Pull request by Leweyse**
Closes #723 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

Fix to #723: Custom scrollbars are not displayed on Firefox (see screenshot).

OS: Windows.

---

## Screenshots

Problem:

t3_bug

Update:

resolved

💯

### CODE REVIEW

**Comment by nexxeln** [comment]
Please format the code using `pnpm format`.

**Comment by STNeto1** [comment]
looks fine on V106.0.3

image

**Comment by juliusmarminge** [comment]
Left scrollbar is still missing on your screenshot

**Comment by nexxeln** [comment]
> Left scrollbar is still missing on your screenshot (not at PC so cant verify)

It's there for me on brave and is on firefox for other people so it should be fine

**Review by nexxeln — APPROVED** [review]

**Comment by STNeto1** [comment]
> Left scrollbar is still missing on your screenshot (not at PC so cant verify)

was just the dark reader extension i think

image

**Review by c-ehrlich — APPROVED** [review]
Works for me on Chrome, Firefox, and Safari. Thanks for fixing this :)

**Comment by Leweyse** [comment]
> Works for me on Chrome, Firefox, and Safari. Thanks for fixing this :)

My pleasure!

**Pull request merged**
