### PR TITLE
fix: search for tsconfig relative to eslintrc

### PR DESCRIPTION
**Pull request by mkreuzmayr**
## ✅ Checklist

- [X] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [X] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] I performed a functional test on my final commit

---

## Changelog

I created a t3-app in an existing monorepo and I expect eslint to use the config file that is in the project and not in the turborepo root. The current `.eslintrc.cjs` always searches for the `tsconfig.json` in the root of the project. I resolved the path to do a relative seach, which is what most people expect if there lies a `tsconfig.json` next to the `eslintrc.cjs`.

💯

### CODE REVIEW

**Comment by Zamiell** [comment]
i can confirm that i do this pattern in my monorepos as well.

**Comment by juliusmarminge** [comment]
don't y'all put this stuff in the root config? i usually do this: https://github.com/t3-oss/create-t3-turbo/blob/bb46ce25a43fb6379f69988ea1f7e14f6e032ebd/.eslintrc.js#L8-L13

**Comment by Zamiell** [comment]
I don't think using the `tsconfigRootDir` option obviates the problem. My monorepo has that specified, yet I still have to use `path.join`.

Furthermore, I don't quite understand your config. Why is the root ESLint extending from each project? That seems backwards. The child ESLint configs should be inheriting from the parent, like how normal TypeScript code would work.

**Comment by Zamiell** [comment]
Also, as a side note, the file should have a cjs extension, not a js extension.

**Comment by mkreuzmayr** [comment]
I agree with @Zamiell 

@juliusmarminge Using a single eslint config that spans your whole monorepo is a bad practice, especially if it grows in complexity. If you only have two similar projects in your repo (e.g. all of them are using React) it may be fine.

For monorepos that contain different projects in them (some React, Svelte and NodeJS) where every project needs a dedicated eslint config, your approach is not viable. In addition, it also defeats the whole project structure if configuration files are outside the project scope in which they are used.

**Comment by mkreuzmayr** [comment]
> Also, as a side note, the file should have a cjs extension, not a js extension.

This should not be a problem as long as `type` is not set to `module` in the `package.json`.

**Comment by Zamiell** [comment]
> This should not be a problem as long as type is not set to module in the package.json.

It's not a problem insofar that it causes any lint errors, but I think it is best practice in 2023 to name your ESLint config file `.eslintrc.cjs` regardless of what underlying package.json settings your have, because it makes it very explicit what the format of the file is, and allows you to refactor your package.json settings in the future without introducing any bugs into your codebase.

**Comment by juliusmarminge** [comment]
The typescript parser options doesnt need to be separate, so I like just specifying the tsconfig paths in root.

As for the rules etc those can extend some common config package and also add new rules on their own (I think I left this as a todo for our monorepo).

Not quite sure what the benefits are of duplicating the tsconfig path in each config?

**Comment by Zamiell** [comment]
> The typescript parser options doesnt need to be separate, so I like just specifying the tsconfig paths in root.

They need to be separate, because each package has a separate tsconfig. You wouldn't want to be linting `foo` with the `tsconfig.json` compiler settings of `bar` - that would cause spurious errors in your codebase and other problems. As I explained earlier, the problem becomes more pronounced when you have a node package and a browser package in the same repo.

**Comment by mkreuzmayr** [comment]
It isn´t about tsconfig´s here, it´s about eslintrc´s. Your root `.eslintrc.cjs` defines the linting rules for A and B. Most projects need seperate eslint configs with different rulesets. But nevertheless, if this way works for you, it´s fine, I do not want to force you into doing it differently.

**Comment by mkreuzmayr** [comment]
Thanks for merging. 🚀

**Pull request merged**
