### PR TITLE
feat: add loggers during dev

### LINKED ISSUE #306: Various ideas to discuss
**Is your feature request related to a problem? Please describe.**
First of all, I'd like to say that I really like this project and appreciate all the work that has been done by the community.
I'm opening this issue to discuss some features that I think could be added (I don't want to spam the issues section).

## Starting from the minor adjustments
1. Dismantle Prisma client on `teardown`, this can be easily done by adding one line:
```ts
// src/pages/api/trpc/[trpc].ts
[...]
import { prisma } from '../../../server/db/client'
export default createNextApiHandler({
  router: appRouter,
  createContext,
  teardown: () => prisma.$disconnect(),
})
```
2. Loggers are really useful during dev: both tRPC and prisma offer some kind of logging. I noticed that @TheoBr already opened an issue about the former (#296). For Prisma, a possible approach may be:
```ts
export const prisma =
  global.prisma ||
  new PrismaClient({
    log:
      env.NODE_ENV === 'development' ? ['query', 'error', 'warn'] : ['error'],
  })

// unsure about this if statement,
// can be improved for the testing env?
if (env.NODE_ENV !== 'production') {
  // prisma middleware to show elapsed time
  prisma.$use(async (params, next) => {
    const before = Date.now()
    const result = await next(params)
    const after = Date.now()
    console.log(
      `Query ${params.model}.${params.action} took ${after - before}ms`
    )

    return result
  })

  global.prisma = prisma
}
```
## Major features
3. Currently all projects scaffolded by ct3a use a session-based strategy for auth.
Do you guys think that having a jwt-based strategy as a option could benefit the project? For example, a possible cli step:
```bash
- next-auth(database-strategy)
- next-auth(jwt-strategy)
- tRPC
- tailwind
- prisma
```
4. Add support for [Per-page layouts](https://nextjs.org/docs/basic-features/layouts#per-page-layouts):
```ts
export type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode
}

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout
}

const MyApp = (({ Component, pageProps }: AppPropsWithLayout) => {
  const getLayout =
    Component.getLayout ?? ((page) => <MainLayout>{page}</MainLayout>)

  return getLayout(<Component {...pageProps} />)
}) as AppType

// at EOF
export default withTRPC<AppRouter>({})(MyApp)
```
5. `context.ts` can be improved, because currently the `req`/`res` object are being passed around for all procedures. PR #186 already fixes this issue but can be improved even further (after the merge maybe). The main problem is in the fact that `createContext` is called for **each** request, so `getServerSession` is called everytime we call the API and even endpoints that don't need to be authenticated will have to wait for the fetching of the user session: this can be solved by passing a function down to all procedures, as such:
```ts
// this code changes a bit of stuff from the PR opened by KATT
interface CreateContextOptions {
  getUserSession: () => Promise<Session | null>
}

export async function createInnerContext(opts: CreateContextOptions) {
  return {
    getUserSession: opts.getUserSession,
    prisma,
  }
}

export async function createContext(opts: CreateNextContextOptions) {
  const getUserSession = async () =>
    await getServerSession(opts.req, opts.res, authOptions)

  return await createInnerContext({
    getUserSession,
  })
}

type Context = inferAsyncReturnType<typeof createContext>

// Creates a normal tRPC router
export const createRouter = () => router<Context>()

// Creates a tRPC router that asserts all queries and mutations are from an authorized user.
// Will throw an unauthorized error if a user is not signed in.
export const createProtectedRouter = () =>
  createRouter().middleware(async ({ ctx, next }) => {
    const session = await ctx.getUserSession()
    if (!session) throw new TRPCError({ code: 'UNAUTHORIZED' })

    return next({
      ctx: {
        ...ctx,
        session, // session is known to be non-null and will be passed to other procedures
      },
    })
  })
```

## Final considerations
I know I have shown a lot of stuff in this single issue (maybe a discussion section would be more approriate!),
but feel free to discuss (and reject) all the points: in particular, point 3 may need a lot of code to be implemented.
If help is needed, I can happily contribute to the project and open PRs.

### PR DESCRIPTION
**Pull request by Gejsi**
Closes #306

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Finishes what's been started on #312.

💯

### CODE REVIEW

**Review by juliusmarminge — APPROVED** [review]
Like it!

I can't reproduce the behavior where the middleware runs multiple times though? Would be nice if we could enable it by default. Leaving commented snippets isn't ideal.

**Comment by Gejsi** [comment]
Simple steps to reproduce the middleware running multiple times:
1. start the app
2. fetch (through `curl` or something else) the `http://localhost:3000/api/examples/` route because it has a simple db query.
3. cause a hot-reload (e.g. change homepage title)
4. re-fetch (step 2)

You can notice the db query in the console goes up by 1 line (in the video from 2 to 3 lines).
However, this isn't really deterministic, a lot of things may lead to this behavior.

Tbh, this isn't that big of a deal, but it can become pretty annoying quickly and maybe even confuse the developer into thinking that there are multiple queries.

I can un-comment the middleware and make a commit, tell me what you think @juliusmarminge.

(sorry if the video is messed up, arch isn't too friendly with these things)

https://user-images.githubusercontent.com/25225304/186997456-d488fc3e-f80b-410a-8565-a2de4d8e3628.mp4

**Comment by juliusmarminge** [comment]
Oh i didnt try editing the app.

Yea remove it and I'll merge this, maybe come back to this later. Maybe post an issue on prisma's side for this?

I tried moving the prisma.$use to a few different places to make sure we only initialized the middleware once, if that was the problem.

**Comment by Gejsi** [comment]
> I'd say remove it and I'll merge this, maybe come back to this later. Maybe post an issue on prisma's side for this?
> 
> I tried moving the prisma.$use to a few different places to make sure we only initialized the middleware once, if that was the problem.

Yeah, I also tried to make it run only once but I couldn't do it.
I'll probably open an issue on prisma and if there is a way to do it I'm gonna open a PR here :smile:

**Comment by juliusmarminge** [comment]
Awesome just [run a changeset](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md#when-youre-done) and I'll merge

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
