### PR TITLE
chore: Add rewrite to www

### PR DESCRIPTION
**Pull request by andreifilip123**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by andreifilip123** [comment]
@juliusmarminge can you allow this to vercel so I can test it there ?

**Comment by juliusmarminge** [comment]
> @juliusmarminge can you allow this to vercel so I can test it there ?

Done

**Comment by andreifilip123** [comment]
I looked into this and currently, while /upgrade rewrites to t3-upgrade, the assets (css, js, fonts) don't really work. 
It may be doable but I'm not sure how.
I found this which might be useful:
https://github.com/vercel/next.js/issues/5602#issuecomment-673382891
https://docs.astro.build/en/guides/integrations-guide/vercel/#vercel-middleware

A mix of these two might work but I'm over my head with this.
I think maybe the middleware file in the www folder + the assetPrefix + rewrites in the upgrade project might work but I'm not sure if that makes sense

**Comment by andreifilip123** [comment]
Also this:
https://github.com/vercel/next.js/issues/5602#issuecomment-986915749

**Pull request closed without merging**
