### PR TITLE
fix: language select layout shift (closes #855)

### LINKED ISSUE #855: bug: layout shift on clicking and clicking out of the language select dropdown
### Provide environment information

Brave browser on Windows 11

### Describe the bug

On clicking and clicking out of the language select dropdown, there is layout shift.

https://user-images.githubusercontent.com/95541290/203685235-12534d19-2fe6-460d-83a5-0446e134f1ee.mp4

### To reproduce

Replicate what's being done in the video

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Seth-McKilla**
Closes #855

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

✅ Updated navbar style to 'fixed' instead of 'flex' to prevent layout shift when selecting the language select dropdown
✅ Added component type of 'div' to the Listbox.Button component within the LanguageSelect component to prevent scrolling when unselected / clicking outside of language select options

---

## Screenshots

test

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Prettier

**Comment by juliusmarminge** [comment]
Looks great. Not on PC so cant test but from your preview it looks to be working 👌👌

**Review by nexxeln — COMMENTED** [review]
something got messed up on index 
index

**Review by nexxeln — COMMENTED** [review]
Also issues with theme toggle now 

theme toggle issue

**Review by nexxeln — COMMENTED** [review]
The exit animation is a bit janky 
janky exit animation

**Comment by asrvd** [comment]
the issue is that you fixed the navbar, so the index is not getting positioned according to nav ig

**Comment by Seth-McKilla** [comment]
Awesome 👌🏻 I'll fix prettier check when I'm back at my PC a bit later

**Comment by asrvd** [comment]
also, cant navigate by tabbing anymore for some reason, it selects the theme toggle after github icon instead of selecting language selector

**Comment by Seth-McKilla** [comment]
Interesting, I narrowed down the layout shift issue to this 'flex':

image

On phone otherwise would just like to line in repo. Removing this flex gets rid of the issue but is likely causing these other issues

**Comment by Seth-McKilla** [comment]
Tried a bunch of different overflow options but couldn't figure out how to keep it flex and not introduce the shift

**Comment by Seth-McKilla** [comment]
Okay after some more digging I think I found the culprit class:

https://github.com/t3-oss/create-t3-app/blob/next/www/src/styles/global.css#L40

test

Removing this line completely fixes the issue without any of the introduced bugs above. I don't see any adverse effects when removing it - @juliusmarminge I see you made this commit ~2 months ago, is there something I'm missing that this resolved? If not I can update the PR, thanks!

**Comment by juliusmarminge** [comment]
> Okay after some more digging I think I found the culprit class:
> 
> 
> 
> https://github.com/t3-oss/create-t3-app/blob/next/www/src/styles/global.css#L40
> 
> 
> 
> test
> 
> 
> 
> Removing this line completely fixes the issue without any of the introduced bugs above. I don't see any adverse effects when removing it - @juliusmarminge I see you made this commit ~2 months ago, is there something I'm missing that this resolved? If not I can update the PR, thanks!

Gitblame don't do me like that 😂

FR though I don't remember putting that there so not sure what it does.

**Comment by Seth-McKilla** [comment]
> > Okay after some more digging I think I found the culprit class:
> > https://github.com/t3-oss/create-t3-app/blob/next/www/src/styles/global.css#L40
> > test
> >       
> >         [
> >           
> >             test
> >           
> >         ](https://user-images.githubusercontent.com/63591760/204090098-aa90dfa6-4206-4c6a-b006-d9660c3c02be.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/63591760/204090098-aa90dfa6-4206-4c6a-b006-d9660c3c02be.gif)
> >         
> >       
> > Removing this line completely fixes the issue without any of the introduced bugs above. I don't see any adverse effects when removing it - @juliusmarminge I see you made this commit ~2 months ago, is there something I'm missing that this resolved? If not I can update the PR, thanks!
> 
> Gitblame don't do me like that 😂
> 
> FR though I don't remember putting that there so not sure what it does.

Haha 🤣 I'm not seeing any weird behavior anywhere but just wanted to double check I wasn't overlooking anything. Scrollbars can be nastly little buggers

**Review by nexxeln — APPROVED** [review]
Nice!

**Review by c-ehrlich — APPROVED** [review]
Wow thanks for catching that!

**Pull request merged**
