### PR TITLE
fix(docs): use custom scrollbar in language selector

### LINKED ISSUE #1002: bug (docs): language selector doesn't use custom scrollbar
### Provide environment information

.

### Describe the bug

image

### To reproduce

go to the website and click the language selector

### Additional information

There is more than one possible solution for this:
1. Display the languages in a grid
2. Make the container as tall as the content (I doubt we will get enough languages that this will become a problem)
3. Use the T3 scrollbar
    - if this is chosen, please make sure that it is also on the correct (right) side in Arabic

If you decide to implement this, feel free decide yourself which is better or propose another solution :)

### PR DESCRIPTION
**Pull request by AyanavaKarmakar**
Closes #1002

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Screenshots

- LTR

image

- RTL

image

💯

### CODE REVIEW

**Review by c-ehrlich — COMMENTED** [review]
Is it possible to get the scrollbar "under" the rounded corner here? (it might not be, but wanted to ask first)

image

**Comment by AyanavaKarmakar** [comment]
> Is it possible to get the scrollbar "under" the rounded corner here? (it might not be, but wanted to ask first)
> 
> image
> 

Not sure if that's possible. Maybe we can make the scrollbar tips rounded using 'scrollbar-thumb-rounded-md', etc so that it doesn't look like it is overflowing out of the dropdown menu. Unfortunately, I don't have my pc with me rn. I will get back to this PR after 25th if that's alright.

**Comment by Yevhenii-Bakhmat** [comment]
i made it rounded in #1007

**Comment by juliusmarminge** [comment]
Superseded by #1007

**Pull request closed without merging**
