### PR TITLE
docs(t3-collection): add tauri-t3-app

### PR DESCRIPTION
**Pull request by AyanavaKarmakar**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Added `tauri-t3-app` to the t3-collection. Provides out-of-the-box "T3 Experience" for those using Next.js as their framework when building [Tauri](https://tauri.app) apps.

---

💯

### CODE REVIEW

**Review by nexxeln — COMMENTED** [review]
How are you running prisma in a webview? Also looks like you're using node, whats the point of using tauri then? Just use electron at that point no?

**Comment by nexxeln** [comment]
Okay cool. What I'm understanding here is that you deploy the server to vercel and the app is an installable version of a website?

**Comment by AyanavaKarmakar** [comment]
> Okay cool. What I'm understanding here is that you deploy the server to vercel and the app is an installable version of a website?

Yep. Let's say, for example, you made a simple TODO app using ct3a, and now you want to use it natively. Instead of using the "chunky" Electron.js, you can simply run,

```sh
npm run tauri init
```

then do some minor tweaks and your native app is ready. However, let's say you're starting from scratch. You can simultaneously develop for both native & web using 

```sh
npm create tauri-app
```
 and some minor tweaks. The template is useful for those who are using Next.js with Tauri for multi-platform deployment and want to use the T3 stack. Kinda like Expo. No need for stitching together stuff. Thought it will be useful for others.

**Comment by nexxeln** [comment]
I'll add it if you add the instructions on how to deploy the server to vercel and how to actually export the app to the readme.

**Review by nexxeln — APPROVED** [review]
amazing

**Pull request merged**
