### PR TITLE
fix: extra whitespace on landing page

### PR DESCRIPTION
**Pull request by iDarkLightning**
## ✅ Checklist

- [X] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [X] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] I performed a functional test on my final commit

---

## Changelog

Display the background pattern via a pseudo-element bg-image instead of an image tag. Fixes unnecessary whitespace on specific screen sizes
---

## Screenshots

**Current**:
image

**Changed**:
image

💯

### CODE REVIEW

**Comment by c-ehrlich** [comment]
I'm not seeing the background at all on the test deployment. But your screenshot of the fix has it. Could you see what's the difference between between your local environment and the deployment?

image
vs
image

**Comment by iDarkLightning** [comment]
Weird, it seems to be trying to find the image on the path `/assets/images/background-image.svg` on the preview deployment. That's giving a 404 which results in the image not being shown. Locally, it works fine and just targets `images/background-image.svg`.

Not sure why this is happening, do you know if this is something to do with the preview deployment system here? I've never faced this issue on vercel before

**Comment by c-ehrlich** [comment]
> ...would love an explanation on why that makes a difference but it seems to be working now

I believe this might be because images are served differently depending on environment  - in staging we build the static site, on your computer it's coming from the development server.

Could check this theory by reverting to the "broken" version, and building / starting the static site locally.

**Review by c-ehrlich — APPROVED** [review]
Looks good, thanks for the contribution :)

**Pull request merged**
