### PR TITLE
feat: add pagination

### PR DESCRIPTION
**Pull request by G3root**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog
add pagination for docs

### CODE REVIEW

**Review by juliusmarminge — APPROVED** [review]
I like it

**Review by nexxeln — CHANGES_REQUESTED** [review]
How about on hover we just add underline, no color changes

**Comment by c-ehrlich** [comment]
> How about on hover we just add underline, no color changes

we're currently doing both underline and color change in both left and right sidebar. imo unless we change those it's good the way it is

**Review by c-ehrlich — COMMENTED** [review]
great feature and clean implementation. i like it a lot.

one suggestion would be to move the hr under the pagination - that seems to be the "standard" way of doing it. for example here's the next beta docs

image

**Comment by nexxeln** [comment]
Run `pnpm format` too

**Comment by G3root** [comment]
@nexxeln Done 👍🏼

**Review by nexxeln — APPROVED** [review]
Looks great

**Pull request merged**
