### PR TITLE
chore(ci): matrix e2e test

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Adds matrix e2e tests (test building every combination)

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Should probably fix the job's name so that it is easier to see what job is what.

**Comment by juliusmarminge** [comment]
what you think @nexxeln ?

**Review by nexxeln — COMMENTED** [review]
So this is like a end to end test for the cli and the app?

**Comment by juliusmarminge** [comment]
> So this is like a end to end test for the cli and the app?

It extends what we have today and scaffolds and builds every combination of applications. Today we test only the app where you select all packages.

**Comment by nexxeln** [comment]
> > So this is like a end to end test for the cli and the app?
> 
> It extends what we have today and scaffolds and builds every combination of applications. Today we test only the app where you select all packages.

Sounds great, ship it!

**Comment by juliusmarminge** [comment]
> > > So this is like a end to end test for the cli and the app?
> 
> > 
> 
> > It extends what we have today and scaffolds and builds every combination of applications. Today we test only the app where you select all packages.
> 
> 
> 
> Sounds great, ship it!

The current setup is a bit messy but it works. Could look into simplifying it later

**Pull request merged**
