### PR TITLE
feat: bumped tailwind from 3.2.7 -> 3.3.0

### LINKED ISSUE #1311: feat: update tailwind from 3.2.7 -> 3.3.3
### Is your feature request related to a problem? Please describe.

New tailwind update just dropped https://tailwindcss.com/blog/tailwindcss-v3-3

### Describe the solution you'd like to see

Update tailwind

### Describe alternate solutions

Dont update tailwind

### Additional information

#

### PR DESCRIPTION
**Pull request by FinnDore**
Closes #1311 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Bumped tailwind version from 3.2.7 -> 3.3.0
---

## Screenshots

💯

### CODE REVIEW

**Review by juliusmarminge — APPROVED** [review]

**Comment by FinnDore** [comment]
image
Do we care about this?

**Comment by FinnDore** [comment]
image
it works!. ( ive moved WWW to use a ts config. will do the same for the cli now. )

**Comment by FinnDore** [comment]
https://github.com/withastro/astro/issues/6695

the last hurdle. Might switch back to a cjs config for WWW for now.

**Comment by FinnDore** [comment]
Dropped the astro tailwind plugin. we have a winner: ( the bg color is to prove the new tw config works in the generated cta app! )
image

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
