### PR TITLE
docs: add "why not `/app`?" FAQ

### PR DESCRIPTION
**Pull request by bdsqqq**
## ✅ Checklist

- [X] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [X] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] I performed a functional test on my final commit

---

## Changelog

Added an FAQ item responding to the common question of "Why aren't you using the `/app` folder from Next.js 13??".

---

## Screenshots

image

💯

### CODE REVIEW

**Comment by bdsqqq** [comment]
Might be worth adding something about "your entire router is hard to port, not a great place to bleed" but didn't know where or how to fit it.

**Comment by bdsqqq** [comment]
https://www.twitch.tv/videos/1654724743?t=00h27m08s is where Theo addresses this on stream btw

**Review by nexxeln — COMMENTED** [review]
Maybe instead of saying "especially in parts as crucial as the router" you can say "your entire router is hard to port, not a great place to bleed"

**Review by TheoBr — APPROVED** [review]
Love the copy for this

**Review by c-ehrlich — COMMENTED** [review]
The "glimpse into the future" thing is a LeeRob quote from near the start of yesterdays stream. Could we get a time stamped YouTube link? Would add a lot of credibility to our point of not supporting /app yet I think.

**Comment by juliusmarminge** [comment]
> The "glimpse into the future" thing is a LeeRob quote from near the start of yesterdays stream. Could we get a time stamped YouTube link? Would add a lot of credibility to our point of not supporting /app yet I think.

https://youtu.be/rnsC-12PVlM?t=818

**Comment by bdsqqq** [comment]
> The "glimpse into the future" thing is a LeeRob quote from near the start of yesterdays stream. Could we get a time stamped YouTube link? Would add a lot of credibility to our point of not supporting /app yet I think.

Agreed, added the timestamped yt link in [83ab253](https://github.com/t3-oss/create-t3-app/pull/765/commits/83ab2539f30c06d523ab9221b9960af5cfc2abed)

**Comment by bdsqqq** [comment]
> Maybe instead of saying "especially in parts as crucial as the router" you can say "your entire router is hard to port, not a great place to bleed"

Nicee, I updated the copy to this and since it's closer to what was said on stream I also added a timestamped yt link to give more context. See: [bb50ca7](https://github.com/t3-oss/create-t3-app/pull/765/commits/bb50ca70dd59811f76412045f0901e52399c63b0)

**Comment by renchris** [comment]
Now that app router is in the Next 13.4 stable release, when are we expecting to see create-t3-app use /app instead of /pages?

**Pull request merged**
