### PR TITLE
fix: Update drizzle config to be up to date with the latest version

### PR DESCRIPTION
**Pull request by gcjbr**
Closes #<issue>

## ✅ Checklist

- [x ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

_ drizzle-config-sqlite.ts, drizzle-config-postgres.ts and drizzle-config-mysql.ts were changed to adhere to [Drizzle's format](https://orm.drizzle.team/kit-docs/overview#configuration)

---

## Screenshots

Screenshot 2024-05-10 at 15 08 25
Screenshot 2024-05-10 at 15 08 32

While running Drizzle Studio we are always asked to update it to the latest version, or it won't show the UI. After tha last update, it's finding an error with the current template configs.

This fixes it.

💯

### CODE REVIEW

**Comment by gcjbr** [comment]
> Can you bump the versions in dependencyVersionMap as well just so that it will always pull ^0.21 no matter what package manager? Thanks!

Done

**Comment by juliusmarminge** [comment]
CI failing

**Comment by juliusmarminge** [comment]
Need to Bump here too https://github.com/t3-oss/create-t3-app/blob/main/cli/src/installers/dependencyVersionMap.ts

**Comment by gcjbr** [comment]
> CI failing

I've bumped the dependencyVersionMap. I see the linter is failing, it's failing locally on the main branch as well, on the same places it's failing here. 

Weird 👁️

**Review by juliusmarminge — APPROVED** [review]

**Comment by juliusmarminge** [comment]
idk why the hell shiki is overriding global Response type...

CleanShot 2024-05-10 at 21 21 24

**Comment by gcjbr** [comment]
> idk why the hell shiki is overriding global Response type...
> 
> CleanShot 2024-05-10 at 21 21 24
> 
> cba to dig in - just added some casts

Right?

Weirdest to me is the unchanged code is also not passing the linting. How the heel did it pass linting on main in the first place? 🥸

**Comment by juliusmarminge** [comment]
okay it was the big lockfile diff that was causing the issues

i reverted the lock file changes and resynced it and thing's are back to normal

**Comment by juliusmarminge** [comment]
idk what pnpm version you're on but you had caused like 6k lines of diff in the lockfile which i reverted https://github.com/t3-oss/create-t3-app/pull/1881/commits/b0e6dfe2dc3b6349608674561ee79e862aefe347

**Comment by juliusmarminge** [comment]
Now we have some failing CI again (that's actually cause of the change)
CleanShot 2024-05-10 at 21 27 01

Can you fix it up so it's passing?

**Comment by gcjbr** [comment]
> idk what pnpm version you're on but you had caused like 6k lines of diff in the lockfile which i reverted [b0e6dfe](https://github.com/t3-oss/create-t3-app/commit/b0e6dfe2dc3b6349608674561ee79e862aefe347)

pnpm -v
8.6.5

Nice catch, thanks!

I'll fix the other test

**Comment by gcjbr** [comment]
@juliusmarminge , done!

Can you tell me your PNPM version, btw?

Just so I don't create a mess in the future

**Comment by juliusmarminge** [comment]
I use corepack so it matches whatever is in package.json#packageManager

**Pull request merged**
