### PR TITLE
fix: fix 404 page on Vercel

### PR DESCRIPTION
**Pull request by PiotrekPKP**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

404 pages should be shown correctly. Now, every page that should a 404 shows bugged landing page.

---

## Screenshots

image

💯

### CODE REVIEW

**Comment by PiotrekPKP** [comment]
As I don't know how deploy is set, I'm not sure where to put the vercel.json file. Also, we'd need to test it first. 
I'd convert it to draft for now

**Comment by juliusmarminge** [comment]
> As I don't know how deploy is set, I'm not sure where to put the `vercel.json` file. Also, we'd need to test it first. 
> 
> I'll convert it to draft for now

Put it in the www folder

**Comment by PiotrekPKP** [comment]
Sure!

**Review by juliusmarminge — APPROVED** [review]
👍

**Pull request merged**
