### PR TITLE
chore: nuke commitlint

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Removing commitlint as I dont think it's necessary. We squash PRs so the individual commits aren't important for the history. We still keep the linter for the PR title.

I'm all for disabling husky all together and just relying on CI but don't feel too strongly about it.

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Happy to revert this commit: https://github.com/t3-oss/create-t3-app/pull/479/commits/3f55dac8b49ec48b20104a5d5b2e3ee861baf117 if you want to keep it.

**Comment by juliusmarminge** [comment]
Happy to revert https://github.com/t3-oss/create-t3-app/pull/479/commits/3f55dac8b49ec48b20104a5d5b2e3ee861baf117 - https://github.com/t3-oss/create-t3-app/pull/479/commits/762798d23ac41d567a2e8ac18d29caaad19ef968 if you want to keep it

**Comment by TheoBr** [comment]
Obviously I support this but I'll leave it up to y'all 🙏

**Comment by c-ehrlich** [comment]
I'd be in favour of keeping the new Astro/Prettier setup. Other than that I think I agree that it's not necessary.

**Comment by juliusmarminge** [comment]
> I'd be in favour of keeping the new Astro/Prettier setup (for the time being). Other than that I think I agree this stuff isn't really necessary.

Did you file an issue for Astro that prettier isn’t run in the IDE for their plugin?

**Comment by nexxeln** [comment]
Yeah I think it makes sense.

**Review by nexxeln — APPROVED** [review]

**Pull request merged**
