### PR TITLE
docs: recommend `node:16-alpine3.16`

### PR DESCRIPTION
**Pull request by nicolomaioli**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Recommend `node:16-alpine3.16` as a base image for Docker, as per issue #975
- Affects all translations

💯

### CODE REVIEW

**Comment by c-ehrlich** [comment]
Thanks for the PR :)

I think it would also be nice to have an explanation in the docs of why we're pinning Alpine to 3.16, maybe with a link to the issue. I'm not sure what's the best approach in terms of adding this but also making it easy for translators to keep their languages up to date. This is the first time we've had that situation, so decided to ask the translators what they think. Will wait for some comments and then let you know.

image

**Comment by nicolomaioli** [comment]
Sounds good! I just replied on Discord so I can see how the conversation evolves 🙏

**Review by c-ehrlich — APPROVED** [review]
Let's get this merged the way it is so that peoples docker deployments stop breaking, and then you can open a separate PR adding an explanation of why we are pinning alpine. This will then "invalidate" this article for the other languages.

I will hopefully set up code owners for translation next month, from then on there should be an easier workflow for this. Am also considering moving the code blocks to their own files as was discussed on Discord.

**Comment by nicolomaioli** [comment]
Awesome, thanks! I'll get something going over the next couple of days, soon as the holiday frenzy settles.

**Pull request merged**
