### PR TITLE
Start tranlsating the docs to arabic.

### PR DESCRIPTION
**Pull request by a4addel**
I have translated a sample of the docs to Arabic,
waiting  for review and coordination to complete the rest of the translation

### CODE REVIEW

**Comment by c-ehrlich** [comment]
Thank you for getting started on this. I'm excited to have the docs available in many languages soon. 

With docs translations, just like any other PR, we want to have at least one reviewer. If there is any other Arabic speaker who would like to help with this, please let us know :)

**Comment by a4addel** [comment]
> Thank you for getting started on this. I'm excited to have the docs available in many languages soon.
> 
> With docs translations, just like any other PR, we want to have at least one reviewer. If there is any other Arabic speaker who would like to help with this, please let us know :)

Guess What my Major is linguistics, I'm in.

**Comment by juliusmarminge** [comment]
There are also a few bits and pieces we need to fix before having i18n docs, such as a language picker, edit links should link to the right language, anything else?

**Comment by a4addel** [comment]
> There are also a few bits and pieces we need to fix before having i18n docs, such as a language picker, edit links should link to the right language, anything else?

let's discuss that on discord.

**Comment by a4addel** [comment]
> There are also a few bits and pieces we need to fix before having i18n docs, such as a language picker, edit links should link to the right language, anything else?

I  wont translate a file until it's ready 100%.

**Pull request closed without merging**
