### PR TITLE
docs: Fix idiom usage in faq.md

### PR DESCRIPTION
**Pull request by jhylacey**
## ✅ Checklist

- [X] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [X] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] I performed a functional test on my final commit

---

## Changelog

Changed wording in idiom from "take as a first class citizen" to "treat as a first class citizen"
---

## Screenshots

image💯

### CODE REVIEW

**Comment by jhylacey** [comment]
Arguably a pedantic PR but cursory Google searches turned up 0 examples of the phrase "take as a first class citizen" in any context, but numerous of "treat as a first class citizen" in the context of programming and English in general.

**Review by nexxeln — APPROVED** [review]

**Comment by nexxeln** [comment]
Fix the conflicts and we can merge!

**Comment by jhylacey** [comment]
> Fix the conflicts and we can merge!

I'm very new to making PR's, how would I do that? In my screen, the option to do is blanked out.

**Comment by jhylacey** [comment]
> Fix the conflicts and we can merge!

Did this fix work? Sorry for the confusion. This is one of my first PRs.

**Review by c-ehrlich — APPROVED** [review]
thanks :)

**Pull request merged**
