### PR TITLE
feat: remove possible trailing slash from appName prompt

### LINKED ISSUE #1460: feat: CLI add a ./ option for the project name
### Is your feature request related to a problem? Please describe.

I want to use ./ to create all the files in my already create directory, but I get this error: `App name must consist of only lowercase alphanumeric characters, '-', and '_'`

### Describe the solution you'd like to see

If I type in the app name ./ all the files are going into the the directory I'm currently in

### Describe alternate solutions

No alternative

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by brunoeduardodev**
Closes #1460

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

_Ignore trailing slashes when prompting the app name_

---

### When prompting `./`

image

### When prompting any path with a trailing slash

image

💯

### CODE REVIEW

**Comment by brunoeduardodev** [comment]
I don't fully love this solution since there's a duplicated checking, both on the validate function and after getting the prompt result, do y'all have any suggestions on this?

**Comment by brunoeduardodev** [comment]
Currently the PR doesn't affect `appName`s provided by the CLI, the project creation works, but the project name, when passing a trailing slash direct to the CLI results in a empty `appName`, in this case might make sense doing this validation on `parseNameAndPath` but I'm not sure if this would be too much, thoughts?

**Comment by c-ehrlich** [comment]
> Currently the PR doesn't affect `appName`s provided by the CLI, the project creation works, but the project name, when passing a trailing slash direct to the CLI results in a empty `appName`, in this case might make sense doing this validation on `parseNameAndPath` but I'm not sure if this would be too much, thoughts?

not sure about implementation details. but in terms of how it works, it should work the same for:
- typing the app name in response to the prompt
- adding it as an arg to the CLI
- CI (same as above I think?)

**Comment by brunoeduardodev** [comment]
I've just changed the implementation to remove the trailing space after the initial `appName` is get, so potential trailing slashes are removed from the prompt, args or ci,

usecase:

#### `./` by args (appName becomes cwd after parsing)
image


#### `./` by prompt (appName becomes cwd after parsing)
image


#### `./some/path/` by args (appName becomes "path" after parsing)
image

#### `./some/path/` by prompt (appName becomes "path" after parsing)
image

**Review by c-ehrlich — CHANGES_REQUESTED** [review]
this looks really clean :)

one remaining issue is that it doesn't catch a name that is just `/` and thus turned into an empty string, causing the command line to crash (if the user submits an empty string the normal way, their app gets named `my_t3_app` instead).

this behaviour should definitely be taken care of, but not sure what's better:
- doing the same thing as when an empty string is provided at the start
- turning an app name of `/` into `.` as it feels like this might be the user intent (they almost certainly didnt intend to init at the root of their file system)
- an error of some sort

**Comment by brunoeduardodev** [comment]
I see, currently the create-t3-app gives a validation error when a user prompts `/`, and when passing `/` through args it goes to the root dir,

So my suggestion would be keeping this behavior, since there might be some kind of weird scenario where it's wanted to create the app through the root,

this would mean we are going to remove trailing slashes only if there's at least 2 characters, do you have thoughts?

**Comment by c-ehrlich** [comment]
> I see, currently the create-t3-app gives a validation error when a user prompts `/`, and when passing `/` through args it goes to the root dir,
> 
> So my suggestion would be keeping this behavior, since there might be some kind of weird scenario where it's wanted to create the app through the root,
> 
> this would mean we are going to remove trailing slashes only if there's at least 2 characters, do you have thoughts?

Sounds good!

**Comment by brunoeduardodev** [comment]
Just added a commit adding this behavior, I wonder if we should give a hint to the user telling then to use `.` if they want to install the project on the current dir.

I've also moved the verification to an util function, not sure if `utils` folder was the best place for that.

### From prompt

image

### From args

image

**Review by c-ehrlich — APPROVED** [review]
This looks good :) Thanks for the PR!

**Pull request merged**
