### PR TITLE
feat: rename index.ts to _app.ts

### PR DESCRIPTION
**Pull request by c-ehrlich**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

The tRPC docs now use the pattern of naming the index router `_app.ts` [[1]](https://trpc.io/docs/v10/merging-routers) [[2]](https://trpc.io/docs/v10/data-transformers#2-add-to-your-inittrpc). This PR updates our template and docs to be the same.

💯

### CODE REVIEW

**Review by juliusmarminge — APPROVED** [review]
I like index more cause you can use the `~/server/router` import but I guess we go with the docs

**Comment by c-ehrlich** [comment]
I don't _love_ the `_app.ts` naming either tbh. But imo if they stick with it, we should use it too.

Could ask the tRPC team what the motivation for this naming is?

**Comment by c-ehrlich** [comment]
Alex made a good point: it comes first in alphabetical order.

**Comment by juliusmarminge** [comment]
Ship it

**Pull request merged**
