### PR TITLE
fix: issue 678 yarn@1 cannot run yarn create t3-app

### LINKED ISSUE #678: bug: `yarn@1` cannot run `yarn create t3-app`
### Provide environment information

System:                                                                                                                   
OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)                                                                         
CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600KF                                                                     
Memory: 12.86 GB / 15.53 GB                                                                                            
Container: Yes                                                                                                          
Shell: 5.0.17 - /bin/bash                                                                                            

Binaries:                                                                                                                 
Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node                                                                  
Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.0/bin/yarn                                                                  
npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm

### Describe the bug

When a user attempts to run `yarn create t3-app` with yarn@1, the project setup script fails. The user can still run `yarn install` afterwards to install dependencies, but I would expect the dependencies to successfully install.

### To reproduce

**Steps**

- Ensure you have yarn v. 1.x.x installed
- Run `yarn create t3-app` and follow the CLI prompts
- When you get to the output `Installing Dependencies...` you will encounter the error

### Additional information

image

### PR DESCRIPTION
**Pull request by PossibleNPC**
fixes the problem described in the issue and updates CLI output to reflect changes to the user

Closes #678 

## ✅ Checklist

- [X] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [X] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] I performed a functional test on my final commit

---

## Changelog

--- Fixed the issue with `yarn@1` not being able to successfully run `yarn create t3-app`
--- Updated the output of the CLI to reflect the differences in the package manager commands of yarn and not-yarn to better inform the user

## Screenshots

Showing the new output of running `yarn` package manager
image

Successful setupwith `yarn`
image

PNPM install language in the CLI
image

💯

### CODE REVIEW

**Review by nexxeln — APPROVED** [review]
lgtm

**Comment by juliusmarminge** [comment]
Let's test if we can `yarn create t3-app@beta` then

**Comment by c-ehrlich** [comment]
thanks for the contribution :)

you will probably get a merge conflict with https://github.com/t3-oss/create-t3-app/pull/673, so after that is merged could you update your branch?

**Comment by PossibleNPC** [comment]
> thanks for the contribution :)
> 
> you will probably get a merge conflict with #673, so after that is merged could you update your branch?

Sure thing, I will be more than happy to do so. Will keep an eye peeled for when 673 is merged.

**Comment by juliusmarminge** [comment]
Conflicts

**Comment by juliusmarminge** [comment]
I believe there is a reference in the logNextStep too?

**Comment by PossibleNPC** [comment]
Merged changes from #673 into my local branch and squashed that merge commit.

Discovered that with the fixes mentioned above, this work-around for `yarn@1` is no longer needed; a simple `yarn start` in the cli directory and not making the changes proposed work as desired. See the following images.

**Verified PNPM is working**
image

**Verified that `Yarn@1` is working**
image

**Proof of generation of `yarn.lock` as expected**
image

**Comment by PossibleNPC** [comment]
> 

In light of this, shall I close this MR and Bug Report? I do not believe a change in either the verbiage of the CLI nor the changes to `install` versus `add` are now needed.

**Comment by c-ehrlich** [comment]
> In light of this, shall I close this PR and Bug Report? I do not believe a change in neither the verbiage of the CLI nor the changes to `install` versus `add` are now needed.

So everything works now, even without the changes in this pr? I see the pros and cons as:
```
+ i believe 'add' is the canonical way of using yarn?
- more code
```

not sure what's better, i'm happy to either merge or close, what does everyone else think?

**Review by juliusmarminge — APPROVED** [review]
I say we go for it. But the logNextStep should also be changed for coherency

**Comment by PossibleNPC** [comment]
I am pretty new to Front-End development, so I might be wrong with my input here.

My understanding is that one of the intents of this CLI tool is to provide a user the capability to install packages required for their spawned project from Create-T3-App with the package manager of their choice.

I think, in this instance, since the `package.json` and everything else gets created as desired, the more clear case is to use `yarn install` versus `yarn add true` because `yarn add ...` is going to install individual packages whereas the other is meant to install all dependencies specified in that `package.json`.

Prior to #673 getting merged in, there were some flags that were getting passed in that made this install fail. Now that those work-arounds are no longer present, I do not believe the issue will happen again, unless there are specific versions of Node that are targeted with needing different params for the package installation step.

So I do not see the need to add this logic in at this time.

**Comment by juliusmarminge** [comment]
I'm not a Yarn user myself, but isn't the conventional way just `yarn`?

**Comment by PossibleNPC** [comment]
> I'm not a Yarn user myself, but isn't the conventional way just `yarn`?

I believe this is correct for `yarn@1` and `yarn@2` . If `yarn` is called without any additional args, it will call `yarn install`. We could make the changes reflect that default behavior with `yarn` if so desired.

**Comment by juliusmarminge** [comment]
> > I'm not a Yarn user myself, but isn't the conventional way just `yarn`?
> 
> 
> 
> I believe this is correct for `yarn@1` and `yarn@2` . If `yarn` is called without any additional args, it will call `yarn install`. We could make the changes reflect that default behavior with `yarn` if so desired.

Sounds good

**Comment by PossibleNPC** [comment]
Made changes to reflect default `yarn` behavior as discussed. Unsure if my squash from merging changes from #673 broke anything in the code; and not entirely sure why it is showing that I changed those files when it was just merged and squashed in.

Let me know if I need to undo my commit.

Otherwise, updated pics to show current output reflecting desired behavior.

**pnpm install**
image

**yarn**
image

**Comment by juliusmarminge** [comment]
Yea looks like you have all the changes from different prs in here too

**Comment by PossibleNPC** [comment]
Closing this PR since I made some mistakes with my local repo and can't seem to get them undone. I will fork the repo with #673 changes, and make a new PR from there with the changes here.

**Pull request closed without merging**
