### PR TITLE
fix(docs): fixed several style issues with docs

### PR DESCRIPTION
**Pull request by iAverages**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Fixed active page in sidebar (Not sure how but seems like I did somehow lol)
Fixed scrollbar in sidebar when on Firefox
Fixed nav header height increasing slightly on small device before breakpoint is hit
Fixed transition delay on mobile when nav menu is open
Fixed sidebar overflowing onto content at specific widths

---

## Screenshots

Firefox scrollbar:
Firefox scrollbar broken
Firefox scrollbar fixed

Nav height increase on small devices:
nav height broken
nav height fixed

Content overflow:
overflow broken
overflow fixed

Active page style
active page style

Mobile nav transition
[Broken](https://avrg.dev/Y85yK.mp4)
[Fixed](https://avrg.dev/3G32T.mp4)

💯

### CODE REVIEW

**Review by nexxeln — APPROVED** [review]
Looks awesome on my laptop

**Comment by kroucher** [comment]
Might just be me, and not sure if it came about in this PR, but mobile menu seems a bit broken for some reason on https://create-t3-app-git-fork-iaverages-next-t3-oss.vercel.app/

Opening the mobile menu from the homepage only has the menu fill half the screen - initially I didn’t think I could scroll at all because I was swiping up on the right side of the screen, only to realise the menu width is restricted for some reason:

C58FD5AB-767A-4F71-85E3-C9FEB3BB6358

When opening the mobile menu from a page from the docs, like https://create-t3-app-git-fork-iaverages-next-t3-oss.vercel.app/en/introduction, this one doesn’t let me scroll at all:

5D01A561-6049-4E8E-8C18-69181846CE15

**Comment by AyanavaKarmakar** [comment]
Yeah, same behavior on Android 12 (Brave & Chrome)

brave

braven't

**Comment by iAverages** [comment]
Thanks for noticing that, can you try again now and see if the issue is fixed? Looks all good on ios + safari.

**Comment by kroucher** [comment]
@iAverages looks great on my end! 👍

**Comment by AyanavaKarmakar** [comment]
### Active Pages feature not working

1. Brave Version: 1.45.118 Chromium: 107.0.5304.91

braveSS

2. Google Chrome Version: 107.0.5304.88 

braven't

It works in dev though 🤔 

dev

@iAverages

**Comment by nexxeln** [comment]
> ### Active Pages feature not working
> 1. Brave Version: 1.45.118 Chromium: 107.0.5304.91
> 
> braveSS
> 
> 2. Google Chrome Version: 107.0.5304.88
> 
> braven't
> 
> It works in dev though 🤔
> 
> dev
> 
> @iAverages

That's so weird

**Comment by nexxeln** [comment]
That's so weird

**Comment by AyanavaKarmakar** [comment]
Faced a similar problem before. Adding the [vercel adapter](https://docs.astro.build/en/guides/deploy/vercel/#adapter-for-ssr) fixed the issue. Worth giving a shot ig.

**Comment by AyanavaKarmakar** [comment]
@iAverages Not working on my end. Can you check again?

notWorking

**Comment by AyanavaKarmakar** [comment]
Yep, that's working. But the buttons on the navbar aren't getting highlighted like this: 

image

In dev: 

https://user-images.githubusercontent.com/89210438/200334334-ed5ceb90-6678-475f-a441-5cb663a96edf.mp4

In prod:

https://user-images.githubusercontent.com/89210438/200334721-09b422ce-d50c-456e-a8b9-564f5bc02400.mp4

**Comment by iAverages** [comment]
Fixed that now, I did not know those had the active page effect.

**Comment by nexxeln** [comment]
Looks good to me. And yes this trailing slash problem is quite annoying, I had made a PR to astro to fix this in their examples, somehow I just forgot about it haha.

Thanks!

**Pull request merged**
