### PR TITLE
docs: Fix Mobile Menu, Light Mode Updated, Copy to Clipboard Fixed

### PR DESCRIPTION
**Pull request by kroucher**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
~- [] I performed a functional test on my final commit~

---

## Changelog

- [x] Mobile Menu Fixed (button now properly shows up on landing page, and goes full screen as expected on mobile)
- [x] Light Mode: Lighter purple to replace to white background
- [x] Copy to Clipboard button no longer expanding size of code block, Icon transitioning correctly

---

## Screenshots

image

--

chrome_csfC4Z5WYc

💯

### CODE REVIEW

**Review by nexxeln — COMMENTED** [review]
Amazing work.
Can we make this a 2x2 grid on the mobile layout? 
image

More padding on the tweet cards. 
image

Some padding between the logo and the line here as well
image

The search bar right now is just white. Maybe a light pink or purple will look good?
image

The links are kind of a very similar color to the background, maybe use an indigo shade for them? 
image

**Comment by kroucher** [comment]
Sweet, thanks for the feedback! Should be able to get these done in the next hour or so 👍

**Comment by juliusmarminge** [comment]
> More padding on the tweet cards.

I would reduce the gap too

**Comment by juliusmarminge** [comment]
For me the mobile nav is still a bit broken

image

**Comment by juliusmarminge** [comment]
Mobile nav on docs works better than on landing pageimage image

**Comment by juliusmarminge** [comment]
Also can we do something about the Next and Prisma icons on darkmode, maybe making them white if they are SVGs?

image

**Comment by kroucher** [comment]
So that line in under the navbar literally only shows up on some screens (like between the emulated iPhone SE, iPhone XR and iPhone 12 Pro, it only shows up on the XR..) Have added some padding regardless, but if we want it rounded, I'll need to add a border on the nav and round it - no big deal. 

I still havent quite put my finger on why the mobile menu acts wonky _only_ on the landing page, still need to get that sorted. Kind of the same as above where it works fine on my phone, but have sometimes replicated it in emulation.

Footer:
image

Tweets:
image

Search:
Light:
image

Dark:
image

**Comment by juliusmarminge** [comment]
Looks awesome nevertheless! Shiiip it. We can iterate on bugs until we publish it :)

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
