### PR TITLE
fix: transitions on docs

### PR DESCRIPTION
**Pull request by iAverages**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

Fixed small transition delay between the stars box and arrow on the right side (Had different transition functions)
Added the same hover effect on left menu items to right menu items
Added transitions to background + nav

---

## Screenshots

_[Screenshots]_

[GH Icon](https://avrg.dev/1Ydp1.mp4)
[Right menu hover](https://avrg.dev/9t2dH.mp4)

💯

### CODE REVIEW

**Comment by iAverages** [comment]
Seems to be a delay with the transition on the stars? I'll find out why that is. Also fix the prettier issue (Appears my plugin isn't picking up the config?)

**Comment by iAverages** [comment]
It appears having the transition on the nav is messing with the other transitions inside the nav, I'll take a look tomorrow and fix it. gn 👋

**Comment by juliusmarminge** [comment]
> It appears having the transition on the nav is messing with the other transitions inside the nav, I'll take a look tomorrow and fix it. gn 👋

should I merge these improvements or you plan on continuing on them?

**Comment by iAverages** [comment]
Should be good to merge now, unless there is any other transition issue you've noticed that I missed.

**Review by juliusmarminge — APPROVED** [review]
looking juicy 🔥

**Pull request merged**
