### PR TITLE
fix: lazy load cookies

### LINKED ISSUE #1599: bug:   7.22.0 next build error TRPCClientError: Dynamic server usage
### Provide environment information

 "ct3aMetadata": {
    "initVersion": "7.22.0"
  },

### Describe the bug

image

### Reproduction repo
.

### To reproduce

when：
- install： `pnpm create t3-app@latest`
- use nextjs  appdir option 
- build：` pnpm build`

### Additional information

_No response_

### LINKED ISSUE #1639: bug: tRPC error boilerplate code deploying to vercel breaks site
### Provide environment information

  System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 80.75 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - /opt/homebrew/bin/node
    npm: 10.2.0 - /opt/homebrew/bin/npm
    pnpm: 8.1.1 - /opt/homebrew/bin/pnpm

### Describe the bug

Used bun create t3-app@latest after upgrading to NextJS 14. I ran it locally and it all worked fine. I then created a repo and tried to deploy to Vercel but I got a build error related to tRPC and an error displayed in the window (Screenshots attached). I then tested this using pnpm and npm and same result. App without tRPC deployed fine. 
Screenshot 2023-10-31 at 4 52 16 PM
image

### Reproduction repo

https://github.com/prestonButton/bbqapp

### To reproduce

This app is just the create-t3-app boilerplate code. I ran bun db:push, bun run dev, and then tried to deploy. and got the errors described above. Just wondering if this is because I am using NextJS 14.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #1599
Closes #1639

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Lazy load cookies in order to not force layout to be forced dynamic

---

## Screenshots

image

💯

### CODE REVIEW

**Comment by bai** [comment]
I've been playing around and I know this is WIP, but just in case wanted to mention that the error is still raised on `pnpm build` on this branch:

```
 << query  #2 post.hello  {
  input: { text: 'from tRPC' },
  result: g [TRPCClientError]: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
```

**Comment by juliusmarminge** [comment]
> I've been playing around and I know this is WIP, but just in case wanted to mention that the error is still raised on `pnpm build` on this branch:
> 
> ```
>  << query  #2 post.hello  {
>   input: { text: 'from tRPC' },
>   result: g [TRPCClientError]: Dynamic server usage: Page couldn't be rendered statically because it used `cookies`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
> ```

What node version?

**Comment by bai** [comment]
21.1.0

**Comment by rileybarabash** [comment]
Experiencing the same issue. Implemented the proposed changes on a brand new project and the deployments are still failing.

Here is the error on Vercel:
```
[97;46m << query [1;97;46m #7 post.hello [0m {
  input: { text: 'from tRPC' },
  result: g [TRPCClientError]: Unexpected token ; in JSON at position 4
      at g.from (/var/task/.next/server/app/page.js:1:25988)
      at /var/task/.next/server/app/page.js:1:29857
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    meta: undefined,
    shape: undefined,
    data: undefined,
    [cause]: SyntaxError: Unexpected token ; in JSON at position 4
        at JSON.parse (<anonymous>)
        at parse (/var/task/.next/server/app/page.js:5:3478)
        at /var/task/.next/server/app/page.js:5:2767
        at o (/var/task/.next/server/app/page.js:5:2906)
        at U (/var/task/.next/server/app/page.js:5:3131)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async I (/var/task/.next/server/app/page.js:5:2987)
        at async L (/var/task/.next/server/app/page.js:5:2615)
  },
  elapsedMs: 20
}
g [TRPCClientError]: Unexpected token ; in JSON at position 4
    at g.from (/var/task/.next/server/app/page.js:1:25988)
    at /var/task/.next/server/app/page.js:1:29857
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: SyntaxError: Unexpected token ; in JSON at position 4
      at JSON.parse (<anonymous>)
      at parse (/var/task/.next/server/app/page.js:5:3478)
      at /var/task/.next/server/app/page.js:5:2767
      at o (/var/task/.next/server/app/page.js:5:2906)
      at U (/var/task/.next/server/app/page.js:5:3131)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async I (/var/task/.next/server/app/page.js:5:2987)
      at async L (/var/task/.next/server/app/page.js:5:2615)
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '1151950604'
}
```

[Repo](https://github.com/onambrosia/core/commit/6630fc90e421f30003028523a7ed10957b55cf95) and the [deployment link](https://core-9emj8cku7-ambrosia-e4d5fc28.vercel.app/)

Runs fine locally in dev mode and production.

**Comment by eastcoasting** [comment]
I tried making these tweaks both on my existing t3-app and on a new project and these edits still do not allow static rendering via `export const dynamic = "error"` or `export const dynamic = "force-static"`

**Comment by danieljpgo** [comment]
I fix it by setting the TRPCReactProvider cookie using window.document.cookie.

**Comment by danieljpgo** [comment]
I fix it by setting the <TRPCReactProvider/> cookie using `window.document.cookie`.

Also, components that need to dynamic, but cookie() is being used within tRPC (warning), I am using:

- export const dynamic = "force-dynamic";
or
- noStore()

Basically Next is trying to generate the static page, but if it is using something that needs to be dynamic, it will not let it be dynamic.

**Comment by juliusmarminge** [comment]
> I fix it by setting the <TRPCReactProvider/> cookie using window.document.cookie.

no window during ssr, which is when we need the cookies if we don't wanna throw 401s

**Comment by juliusmarminge** [comment]
Concluded this wasn't actually the fix I thought it was

**Pull request closed without merging**
