### PR TITLE
chore(docs): some improvements to landing

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #<issue>

## ✅ Checklist

- [ ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [ ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Changes:

- Bit more space to the left of logo, made it more round
- Removed bg on searchbar so it blends in more, added hover state and changed cursor
- Made header fit on 3 lines
- Bit more space on the "Stack"-titles, fixed Typescript Icon and reordered the cards
- Added an external icon to the Read more so that it's clear you're leaving the page
- Made inactive bullets more apparent on the TweetSlide

CleanShot 2022-09-20 at 23 47 07@2x

**Review by minsk-dev — APPROVED** [review]

**Comment by c-ehrlich** [comment]
- header looks great
- can "opinionated, full-stack, typesafe" be one line without becoming too wide? I think the title would hit harder that way
- buttons under the header are ok imo
- cli section looks great
- trpc logo seems to have different spacing than the other ones? every other logo is horizontally aligned to the text below it, trpc one looks offset to the right a few pixels. other than that i like those cards
- tweetslide buttons could be a bit close to the tweet, also maybe a bit bigger?

overall its amazing how good this looks. real professional.

**Comment by juliusmarminge** [comment]
> * can "opinionated, full-stack, typesafe" be one line without becoming too wide? I think the title would hit harder that way

Don't think so, the title is already `max-w-4xl`, don't think going wider would be very nice for readers etc.

> * trpc logo seems to have different spacing than the other ones? every other logo is horizontally aligned to the text below it, trpc one looks offset to the right a few pixels. other than that i like those cards

weird, will look into it real quick

> * tweetslide buttons could be a bit close to the tweet, also maybe a bit bigger?

good catch, didn't even notice that but looks much better with less margin 👍🏼

**Comment by nexxeln** [comment]
> > * can "opinionated, full-stack, typesafe" be one line without becoming too wide? I think the title would hit harder that way
> 
> Don't think so, the title is already `max-w-4xl`, don't think going wider would be very nice for readers etc.
> 
> > * trpc logo seems to have different spacing than the other ones? every other logo is horizontally aligned to the text below it, trpc one looks offset to the right a few pixels. other than that i like those cards
> 
> weird, will look into it real quick
> 
> EDIT: i think they are the same, maybe it should be more or less so it doesn't look like it should be aligned but isn't? CleanShot 2022-09-21 at 00 24 32@2x
> 
> > * tweetslide buttons could be a bit close to the tweet, also maybe a bit bigger?
> 
> good catch, didn't even notice that but looks much better with less margin 👍🏼

I think this is fine.

**Review by nexxeln — COMMENTED** [review]
Everything looks great. Really professional. I was just wondering if we really need opinionated in the heading. I think if we remove it, it will look better and also will be concise.

**Comment by nexxeln** [comment]
Can we also maybe increase the font size in the terminal demo component? It is really hard to read atm.

**Comment by PiotrekPKP** [comment]
image
I think with longer tweets the dots are too close to the actual tweet. Just a feedback ;)

**Comment by juliusmarminge** [comment]
> Everything looks great. Really professional. I was just wondering if we really need opinionated in the heading. I think if we remove it, it will look better and also will be concise.

CleanShot 2022-09-21 at 12 10 04@2x

**Review by nexxeln — APPROVED** [review]

**Pull request merged**
