### PR TITLE
feat: construct `serverEnv`, like we do with `clientEnv` #1000

### PR DESCRIPTION
**Pull request by iduuck**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- see #1000 

💯

### CODE REVIEW

**Review by juliusmarminge — CHANGES_REQUESTED** [review]
We shouldnt need 2 separate objects right? Destruction can be in a single object shared with both server and client?

Ideally some comment saying you only need manual destruction for certain use-cases, and not require all envs to be destructured, i.e:

```ts
// schema.mjs
const destructured = {
  FOO: process.env.FOO,
  NEXT_PUBLIC_BAR: process.env.NEXT_PUBLIC_BAR,
}

const serverSchema = z.object({
  FOO: z.string(),
  BAZ: z.coerce.boolean(),
});

// server.mjs
serverSchema.parse({
  ...process.env,
  ...destructured
});
```

**Comment by iduuck** [comment]
I get what you mean, @juliusmarminge. However, I think like this it could be misleading. What we could do, is using the `clientEnv` and extending the `serverEnv` with it.

Like:
```
const clientEnv = { /* ... */ };
const serverEnv = { ...clientEnv, BAZ: process.env.BAZ };
```

**Also:** We would be facing some issues with the validation on the middleware-side. When we only add the middleware environment variables one-by-one, it would be giving us schema validation errors, when using on the middleware (because – in your case – `BAZ` wouldn't be available at the runtime of the middleware).

**Comment by juliusmarminge** [comment]
Fair points. I didnt think of that. I just want to make sure we provide as good DX as possible as many will think its annoying to do this many steps "just to get rid of `| undefined` 🤔

**Comment by iduuck** [comment]
What `| undefined` are you referring to, the one in the declaration of `serverEnv`?

Btw: Do you know, why the build is failing with a wrong import (working for me locally).

**Comment by juliusmarminge** [comment]
> What `| undefined` are you referring to, the one in the declaration of `serverEnv`?

So I guess where I'm going is if I need to do too much work to get it running in the first place, maybe I'd be fine with using `process.env` in edge-runtimes and just take the non-null assertion - or maybe we could get #404 working which would type it properly.

```ts
// in some edge function, e.g. 'src/middleware.ts'
const baz1 = process.env.BAZ;
//    ^? -> string | undefined


const baz2 = process.env.BAZ!;
//^? -> string
```

Either would be fine since the variable have been validated to be present during build time.

Maybe I'm drifting here and this isn't a problem for others? I just wanna make sure we don't make it too much work to get environment variables to work or else people might just nuke it all and use `process.env` for everything 🤔 

> Btw: Do you know, why the build is failing with a wrong import (working for me locally).

You haven't defined the `serverEnv` object in the other schema files, just the base one.

**Comment by iduuck** [comment]
I personally wouldn't want to use the non-null assertion throughout my application. Also for the purpose of the env validation, that t3 offers, I am sure there are use-cases, which would be awesome to have default's for.

So, just using `process.env` isn't feasable (again, personally).

**Comment by juliusmarminge** [comment]
Yea all valid points - curious how many apps use the `middleware.ts` file and if it's warranted to include this by default - the `schema.mjs` file is already kinda scary as it is 🤔 Although I guess this will get more and more relevant as edge runtime becomes more popular to use for more stuff... Maybe we should file an issue to https://github.com/vercel/next.js and see why this is the case - maybe they are open to change it?

**Comment by iduuck** [comment]
I think [this issue](https://github.com/vercel/next.js/issues/30612#issuecomment-955065804) is giving us the reason.

> This is related to how _middleware.ts is webpack transformed by the middleware-plugin.ts.
Only when you access an env var directly you will get the value. You can't destructure from process.env or get the whole object. I am not sure if this behaviour is intended or should be mentioned in the docs.

I think this is due to the nature of the `DefinePlugin` of webpack. However, with turbopack, I am curious, if this is working?

**Comment by iduuck** [comment]
What's the plan to go for? Asking Next.js team first and implementing the PR for now? Or are we not wanting to implement the PR as is?

**Comment by juliusmarminge** [comment]
> What's the plan to go for? Asking Next.js team first and implementing the PR for now? Or are we not wanting to implement the PR as is?

I think this is the best approach even though I'm not a fan of the extra step - but that seems to be out of our hands unfortunately...

Go ahead and fix this up and we can ship it if no-one else has any objections? @c-ehrlich @nexxeln

**Comment by nexxeln** [comment]
> > What's the plan to go for? Asking Next.js team first and implementing the PR for now? Or are we not wanting to implement the PR as is?
> 
> I think this is the best approach even though I'm not a fan of the extra step - but that seems to be out of our hands unfortunately...
> 
> Go ahead and fix this up and we can ship it if no-one else has any objections? @c-ehrlich @nexxeln

Sounds good to me

**Comment by iduuck** [comment]
OK, guys. 
- [x] I updated the code at the docs (unfortunately, I am only speaking english of all the doc languages, so I was not able to change the text for the other languages)
- [x] Synchronized upstream
- [x] Fixed all issues from the tests

**Review by juliusmarminge — APPROVED** [review]
👍👍

**Comment by juliusmarminge** [comment]
Seems like you've disabled maintainers edit priviledges so i cant update your branch

**Comment by c-ehrlich** [comment]
> > What's the plan to go for? Asking Next.js team first and implementing the PR for now? Or are we not wanting to implement the PR as is?
> 
> I think this is the best approach even though I'm not a fan of the extra step - but that seems to be out of our hands unfortunately...
> 
> Go ahead and fix this up and we can ship it if no-one else has any objections? @c-ehrlich @nexxeln

Bit late but I agree with this

**Comment by iduuck** [comment]
> Seems like you've disabled maintainers edit priviledges so i cant update your branch

How am I able to enable this? This is a repository from my company, so could be that this is the the case company-wide? Couldn't find a way to enable this?

**Comment by juliusmarminge** [comment]
Should be on the right side where you request reviews etc

**Comment by iduuck** [comment]
CleanShot 2023-01-08 at 19 51 22@2x
 unfortunately nothing there, would have activated this then ...

**Comment by juliusmarminge** [comment]
It's there when you create the PR. Should be a way to update it after creation too??

CleanShot 2023-01-08 at 19 55 14

**Pull request merged**
