### PR TITLE
docs: portuguese netlify page translation

### PR DESCRIPTION
**Pull request by MattFerreira18**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog
 Hey, what's up everyone?! 

 This PR adds the portuguese translation of [Netlify Deployment](https://create.t3.gg/en/deployment/netlify) page and also removes duplicated texts and fixes some typos in the [t3 collection](https://create.t3.gg/pt/t3-collection) page.

### CODE REVIEW

**Comment by Sn0wye** [comment]
> Sorry for missing this PR until now. This should hopefully be the last time that translators need to be tagged for review manually :)
> @claudiofreitas @minsk-dev @Sn0wye @victoriaquasar

Hey man, don't worry! You can tag me whenever you want, and I'll do the job as soon as possible!

**Review by Sn0wye — APPROVED** [review]
LGTM! Bom trabalho 👍🏻

**Review by c-ehrlich — APPROVED** [review]
Thanks :)

**Comment by c-ehrlich** [comment]
@MattFerreira18 thanks for your contribution! Would you like to be added to the codeowners for the Portuguese translation? Being a codeowner means you get a notification when there is a PR that changes files in your language, so you can review it.

**Comment by MattFerreira18** [comment]
> @MattFerreira18 thanks for your contribution! Would you like to be added to the codeowners for the Portuguese translation? Being a codeowner means you get a notification when there is a PR that changes files in your language, so you can review it.

@c-ehrlich thanks for the invitation bro. I would really like to be able to help more this project.

**Pull request merged**
