### PR TITLE
feat: updated tailwind and replaced cjs config with a ts one

### PR DESCRIPTION
**Pull request by FinnDore**
Closes #<issue>

## ✅ Checklist

- [ ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by FinnDore** [comment]
Need to update the site aswell. wont update any classnames though.

**Comment by FinnDore** [comment]
Places where new end and start classes can be used:

https://github.com/FinnDore/create-t3-app/blob/dd65588c1f05c3203f9ce52b8cd0a5e3f191d1b1/www/src/components/accessibility/jumpToContent.astro#L7
https://github.com/FinnDore/create-t3-app/blob/dd65588c1f05c3203f9ce52b8cd0a5e3f191d1b1/www/src/components/navigation/githubIcon.astro#L34

**Comment by juliusmarminge** [comment]
Looks like you need to change the tailwind installer to pick the new ts file

**Comment by FinnDore** [comment]
Prettier donn like it lmao. Will fix in a sec
```
[error] src/pages/ru/usage/index.astro: /Users/finn/Documents/GitHub/create-t3-app/www/tailwind.config.ts:1
[error] import { Config } from "tailwindcss";
[error] ^^^^^^
[error]
[error] SyntaxError: Cannot use import statement outside a module
```

**Comment by FinnDore** [comment]
Im actually unsure if `prettier-plugin-tailwind` supports a .ts file config yet.  These errors are coming form that and once i stop pointing at the `tailwind` config from the `prettier` config no errors but all the classnames get unformatted.

**Comment by FinnDore** [comment]
Just upgraded a sperate t3 project and the .ts `tailwind` config file works even when referened from the `prettier` config. formatting:
`<div className="absolute z-10 h-1/3 w-full classname some-other-class bg-gradient-to-b from-white to-transparent dark:from-black"></div>`
to
`<div className="classname some-other-class absolute z-10 h-1/3 w-full bg-gradient-to-b from-white to-transparent dark:from-black"></div>`

**Comment by FinnDore** [comment]
> > Im actually unsure if `prettier-plugin-tailwind` supports a .ts file config yet. These errors are coming form that and once i stop pointing at the `tailwind` config from the `prettier` config no errors but all the classnames get unformatted.
> 
> oh shit...

nah i think im chatting shit

**Comment by juliusmarminge** [comment]
> Just upgraded a sperate t3 project and the .ts `tailwind` config file works even when referened from the `prettier` config. formatting: `<div className="absolute z-10 h-1/3 w-full classname some-other-class bg-gradient-to-b from-white to-transparent dark:from-black"></div>` to `<div className="classname some-other-class absolute z-10 h-1/3 w-full bg-gradient-to-b from-white to-transparent dark:from-black"></div>`

im doing t3-turbo as we speak and seems to work so far

**Comment by FinnDore** [comment]
Talkin with @juliusmarminge removing the line pointing towards the prettier config works ( we are confident, just need ot check this fully ).

now the template are failing the formatting

**Comment by FinnDore** [comment]
Nah im still dubious that its  not formatting classes properly. All these files were reformatted but they must have had the correct formatting before?
image

**Comment by juliusmarminge** [comment]
> Nah im still dubious that its not formatting classes properly. All these files were reformatted but they must have had the correct formatting before? image

aah - the tailwindConfig prop might be necessary for Astro? Are React files formatting properly??

**Comment by FinnDore** [comment]
No i dont think so
image
image

**Comment by FinnDore** [comment]
This pr has to much noise and to many formatting changes ill open another one just for the version bump we mentioned on discord

**Pull request closed without merging**
