### PR TITLE
docs: add Discuss

### PR DESCRIPTION
**Pull request by cweiqi27**
Discuss is a forum like Reddit in dark theme. 

note: Hi I'm still pretty much a noob and still learning a lot of things. This is my first ever web app that I developed with Next.js + TS, and the first to be deployed on the cloud. I know it's still kinda scuffed and laggy and I'm still trying to optimize it, but it would be cool if this app could be featured here as this is my first attempt to contributing to open source. You guys made an awesome stack and I learned a lot about best practices especially watching Theo's videos and stream.

Closes #<issue>

## ✅ Checklist

- [✅] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [✅] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [✅] I performed a functional test on my final commit

---

## Changelog

_Added my project's info in the T3 Collection page_

---

## Screenshots

_image_

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Run prettier and reoslve conflicts please 🙏🏼

**Comment by cweiqi27** [comment]
lol hope im doing this right

**Comment by estubmo** [comment]
Norwegian translation looks good

**Comment by juliusmarminge** [comment]
looks like you messed up a merge.

i'll close and you can reopen

**Pull request closed without merging**
