### PR TITLE
fix: glitchy language picker

### LINKED ISSUE #972: bug: docs - language picker is glitchy
### Describe the bug

The language picker...
- has a visual glitch where it looks like all elements are focused and they are spaced incorrectly
- doesn't close when clicking outside of it

https://user-images.githubusercontent.com/8353666/207427872-d513ed82-494b-4bbc-a07d-831e25e33f62.mov

It seems like the bug was introduced in this PR: https://github.com/t3-oss/create-t3-app/pull/886

The best solution would: 
- fix this
- don't break tabindex/accessibility

To what it looked like in a branch before this bug was introduced, look at: https://create-t3-hcy7tn3ev-t3-oss.vercel.app/en/introduction

### To reproduce

- go to https://create.t3.gg/en/introduction
- click the language picker

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by LemmyMwaura**
## Description 
Closes #972. Everything works as expected.

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Screenshots
https://user-images.githubusercontent.com/20738858/207672671-e5845bfb-a945-4833-9090-6892912ca015.mp4

### CODE REVIEW

**Comment by c-ehrlich** [comment]
Thanks for the PR. Currently it fixes the appearance during regular browsing, but there is no focus ring at all during keyboard navigation.

https://user-images.githubusercontent.com/8353666/207718573-e252317a-5cb7-4c31-a810-cc18206e4735.mp4

**Comment by LemmyMwaura** [comment]
Ooh I completely missed that. I'll update this to handle that @c-ehrlich

**Comment by LemmyMwaura** [comment]
@c-ehrlich Added the focus back during keyboard navigation to the Listbox button. I'm not sure if it's needed in the list option but adding it there is what introduces that bug so for now, I've left it as is.

https://user-images.githubusercontent.com/20738858/207812834-8b7dd37f-ad00-4c54-8aa6-c2ad8370ae42.mp4

**Comment by nexxeln** [comment]
That seems to work. I think we could also have a better focus state indication for selecting a new language. Currently its the same the currently selected one.

https://user-images.githubusercontent.com/95541290/207870894-279b90ba-074e-4e23-af37-0381a9bb1b67.mp4

**Comment by LemmyMwaura** [comment]
@nexxeln Do you have a specific color in mind or should i just pick whatever feels natural.

**Comment by c-ehrlich** [comment]
Looks great now! Just one last thing, I think it should prioritize the "selected item" grey background over the "language you're using" purple background when both are true.

https://user-images.githubusercontent.com/8353666/207957695-2e2206e2-507c-4886-bc66-8fc8aae0e87c.mov

**Comment by LemmyMwaura** [comment]
We now prioritise the selected over the active state.

**Review by c-ehrlich — APPROVED** [review]
Works great now. Thanks!

**Pull request merged**
