### PR TITLE
fix: rtl breadcrumbs, "on this page", env var folder structure

### PR DESCRIPTION
**Pull request by c-ehrlich**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Fixes for RTL
- breadcrumbs arrows pointing the wrong way
- "on this page" arrow pointing the wrong way
- "on this page" popover having bad spacing and scrollbar on the wrong side
- env vars folder structure ┫character pointing the wrong way

---

## Screenshots

image

image

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
I dont have a clue what RTL should look like do I'll let someone else approve this

**Review by Sboonny — COMMENTED** [review]
Thank you, awesome work 👍 

Edit: because I am lazy 😅 and don't want to open new issue, Is possible to add margin between search icon and the search text in this PR?

image


Or do I open a new issue/pr?

**Comment by Sboonny** [comment]
juliusmarminge, here is an article about how to style the page in RTL https://rtlstyling.com/posts/rtl-styling, because if someone opens an issue, you can see if they are legit or a troll.

Btw, c-ehrlich is doing awesome job so far, keep it up.

**Comment by c-ehrlich** [comment]
> Thank you, awesome work 👍
> 
> Edit: because I am lazy 😅 and don't want to open new issue, Is possible to add margin between search icon and the search text in this PR?
> 
> image
> 
> Or do I open a new issue/pr?

styling algolia is a bit annoying because it's a premade component with a lot of its own styles.

i want to fix it of course, but would prefer to do it in a separate PR in the future. that way we can get the changes from this PR in sooner.

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
