### PR TITLE
feat: trpc next middleware

### LINKED ISSUE #38: Scaffold NextAuth TRPC getSession middleware if both are selected.
If NextAuth and TRPC are both selected, It's very likely that the user wants to have protected routes/queries.

The TRPC middleware to enable to enable protected routes/queries should be included so users don't have to write the boilerplate code themselves.

There's an example on the [TRPC Kitchen Sink](https://kitchen-sink.trpc.io/next-auth) site.

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #38 

Sorry, I messed up the previous PR (#74).

### CODE REVIEW

**Comment by iDarkLightning** [comment]
It's nicer to implement auth with the [route metadata](https://trpc.io/docs/metadata) feature in my opinion since it enabled routes to easily opt in and out of requiring authentication

**Comment by juliusmarminge** [comment]
Good call. Made a poll on Discord to see which is more used

**Comment by iDarkLightning** [comment]
Yeah performance wise meta might be slightly worse considering that. As far as I am aware you are correct that the middleware will only run for endpoints inserted after the middleware (unless there's some technicalities I'm missing).

**Comment by nexxeln** [comment]
Is this ready to be merged now?

**Comment by juliusmarminge** [comment]
Versioning and changelog left

**Comment by nexxeln** [comment]
Alright

**Comment by nexxeln** [comment]
Thanks!

**Pull request merged**
