### PR TITLE
feat: add standard-version for generating changelog + bump package.json

### PR DESCRIPTION
**Pull request by Fedeorlandau**
So I've added [standard-version](https://github.com/conventional-changelog/standard-version) which is well known for generating changelog from commits and bumping your package.json to the correct version depending on the commits you've added.

`pnpm release`

image

Changelog example:

# Changelog

All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.

### Features

- add CONTRIBUTING.md for newcomers ([99f8220](https://github.com/nexxeln/create-t3-app/commit/99f8220f83a6363e5aab6c0ec33260eb059c9643))
- add inferQueryResponse helper for tRPC ([748800f](https://github.com/nexxeln/create-t3-app/commit/748800f060031da58ce2b45bd65e4fd83266ce5c))
- add main as initial branch ([7b94005](https://github.com/nexxeln/create-t3-app/commit/7b94005fd515d140176e639a487ab5035a290125))
- add next-auth config to env-example [#108](https://github.com/nexxeln/create-t3-app/issues/108) ([c3ab997](https://github.com/nexxeln/create-t3-app/commit/c3ab997f149ee3635d2d33a67650e95e04877d5b))
- add standard-version ([883964b](https://github.com/nexxeln/create-t3-app/commit/883964bf9f990f9c7a2eac27add0a86e6fb99129))
- add tRPC inference helper docs commment on utils ([3e784cb](https://github.com/nexxeln/create-t3-app/commit/3e784cbf3f9b4f6eeb4441a881ebbd028f311957))
- added windows build support ([29acbf8](https://github.com/nexxeln/create-t3-app/commit/29acbf816c69f980454568946fba1afea6be114c))
- better ui for templates ([e2e8c7e](https://github.com/nexxeln/create-t3-app/commit/e2e8c7eeeab576d730cd1c7e397497460c1787e0))
- check if dir is empty ([71bbdba](https://github.com/nexxeln/create-t3-app/commit/71bbdbae564d6e7df4b08645db59a8364b891b99))
- make the ui symmetric ([19df71e](https://github.com/nexxeln/create-t3-app/commit/19df71ec53fd64e60b27ecd055cd9f0c6acc4a63))

### Bug Fixes

- add newline at the end of the file ([64eee1c](https://github.com/nexxeln/create-t3-app/commit/64eee1c8058aa5d2ec29fc1903ee63819fa8fc9d))
- **cli:** use correct spelling, fix short choices ([7776aa9](https://github.com/nexxeln/create-t3-app/commit/7776aa9fc03293f27d9e27808cd03810f96ccc33))
- docs wrong format ([3d2dbb0](https://github.com/nexxeln/create-t3-app/commit/3d2dbb06cadb42d24f134ce09edc5a371d79aff9))
- eslint warning (import/no-anonymous-default-export) ([a1cce55](https://github.com/nexxeln/create-t3-app/commit/a1cce5546a8fd6efb79c65a2f2b52d4c597dafd0))
- handle git projects correctly ([3ed897f](https://github.com/nexxeln/create-t3-app/commit/3ed897ff49c06f6d70d49aee31d5c3741fced96e))
- **markup:** multiple h1 replaced to h2 ([6bf9040](https://github.com/nexxeln/create-t3-app/commit/6bf90407b9a9774348a77927d37c47f3ded5552a))
- provide cwd inside git init exec call ([9679492](https://github.com/nexxeln/create-t3-app/commit/9679492ebd9175973c99d647cf11a4f1b979a505))
- remove unncesary import on auth router ([abdc61f](https://github.com/nexxeln/create-t3-app/commit/abdc61ffc18dd4f1e82f3fc02cd87a2144d0cc03))
- standardize log messages ([83a13b9](https://github.com/nexxeln/create-t3-app/commit/83a13b9963f83317a62e3eeaed14dd5e2cb45344))
- **templates:** h1 restored ([e51e03d](https://github.com/nexxeln/create-t3-app/commit/e51e03d93a899674bef839ddb215a36e62397e26))
- update templates ([4418f1d](https://github.com/nexxeln/create-t3-app/commit/4418f1db06a29050293f0d4dd16a1347d34c6cf9))

### Minor Changes

- improve ui examples of template app

### CODE REVIEW

**Comment by juliusmarminge** [comment]
I'll let @nexxeln approve these (this and #126) but looks good to me.

**Comment by nexxeln** [comment]
Does this conflict with `changeset` in any way?

**Comment by Fedeorlandau** [comment]
> Does this conflict with `changeset` in any way?

Kind of. While `changeset` allows you to update your version and changelog manually, `standard-version` automatically detects if a patch, minor, or major version is required based on the commit types. If you only have bug fixes, it'll automatically bump a patch version. If you add a feature, it'll bump the minor version. For any breaking change, it'll bump the major.

`standard-version` also generates the changelog automatically for you. You can see it in the example above.

**Comment by Fedeorlandau** [comment]
Done!

**Pull request merged**
