### PR TITLE
fix(nextauth-drizzle): changed varchar to text on drizzle nextauth to prevent auth errors

### LINKED ISSUE #1485: bug: nextauth drizzle fields are too short
### Provide environment information

    "initVersion": "7.13.2-beta.966c687"

### Describe the bug

when authenticating with google an error saying that certain fields were too short for the given values. 

### Reproduction repo

https://github.com/nextauthjs/next-auth/issues/4734

### To reproduce

try authenticating with google

### Additional information

Super simple fix already have a pr in to fix it. Just created the issue because it asks for an issue number when you create a PR. It's also my first OSS contribution please tell me if I have done anything wrong.

### PR DESCRIPTION
**Pull request by xiften**
Closes #1485 

## ✅ Checklist

- [| ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [ |] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [| ] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_
in the nextauth drizzle template I changes varchar to text on some fields to prevent errors when authenticating
---

### CODE REVIEW

**Comment by c-ehrlich** [comment]
Are there currently errors when authenticating? I checked out the #1461 branch recently and auth worked for me.

**Comment by juliusmarminge** [comment]
255 should be more than enough for tokens?

**Comment by xiften** [comment]
I'm experiencing the error when using google for auth. It's already a documented issue nextauthjs/next-auth#4734. Can't record the error since I'm out of town and don't have my computer.

**Comment by chungweileong94** [comment]
> 255 should be more than enough for tokens?

Yeah, it was the case before. But having to try it myself and seems like it's no longer the case, at least for Google OAuth.

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
