### PR TITLE
docs: add typescript, nextjs, remove old style tags

### PR DESCRIPTION
**Pull request by kroucher**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
~- [ ] I performed a functional test on my final commit~

---

## Changelog

- Add content to TypeScript page
- Add content to NextJS page
- Remove all remaining <style> tags (except for one required for a non-JS mobile menu toggle)
- Fixed 'More Menu' visibility (wasn't visible between medium-large screen sizes)

‼️ Not super satisfied with the TypeScript content so far, but also wouldn't call myself a pro TypeScript user, feedback (and possibly more info) would be super appreciated 

This just leaves tRPC before all pages have at _something_ on them 🎉
---

## TypeScript

image
image

## NextJS

image
image

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
image

**Comment by juliusmarminge** [comment]
When reading Next.js text I noticed we have removed the 'Powered by Vercel' text which I think we are required to have right?

**Comment by nexxeln** [comment]
> When reading Next.js text I noticed we have removed the 'Powered by Vercel' text which I think we are required to have right?

I think we can have that in the footer on every page

**Review by nexxeln — COMMENTED** [review]
The search bar looks kinda weird in the home page, can we make that consistent? Also the algolia search interface doesn't really match our theme, is it possible to change it?

I think the typescript section we can also talk about how it will help you be more productive and write better code and software. Other than that the content looks really good. I just had some styling suggestions

- Maybe we can make the selected text background the shade of pink we're using 
image

- Maybe we can change the styling of the quote too? Also feels kind of out of place.
image

- Custom scrollbars maybe?
image

**Comment by kroucher** [comment]
> When reading Next.js text I noticed we have removed the 'Powered by Vercel' text which I think we are required to have right?

✅ "Powered by Vercel" added to footer

**Comment by kroucher** [comment]
> The search bar looks kinda weird in the home page, can we make that consistent? Also the algolia search interface doesn't really match our theme, is it possible to change it?
> 
Algolia/Docsearch provide an npm package which just contains .CSS files, so I've pulled them into the `styles/algolia` directory and imported where required instead. These contains the theming (albeit regular css) for Algolia search box/modal. I've updated it but could likely use another pair of eyes

> I think the typescript section we can also talk about how it will help you be more productive and write better code and software. Other than that the content looks really good. I just had some styling suggestions
> 

✅ Added a bit more on how it makes you more productive:

"It is, perhaps, the tool that provides the most productivity to developers; providing documentation of the code you’re writing or consuming directly in your editor, and having instant feedback as you inevitably make mistakes is absolutely priceless."

> * Maybe we can make the selected text background the shade of pink we're using
> 
> image
> 

✅ `selection:` styles added, for both light and dark theme

> * Maybe we can change the styling of the quote too? Also feels kind of out of place.
> 
> image
> 

✅ Quote styling updated

> * Custom scrollbars maybe?
> 
> image

✅ Custom scrollbars added

**Review by nexxeln — COMMENTED** [review]
I think we should put this quote above "What is TypeScript". It does not fit in inference.

image

The rest looks awesome!

**Comment by kroucher** [comment]
> 

That's b

> I think we should put this quote above "What is TypeScript". It does not fit in inference.
> 
> image
> 
> The rest looks awesome!

Thanks for the feedback guys!

Thats been updated now, I realised light mode quote looked trash so that's been fixed now too.

**Comment by juliusmarminge** [comment]
I say ship it

**Comment by nexxeln** [comment]
Yep!

**Pull request merged**
