### PR TITLE
refactor(website): nav & landing

### PR DESCRIPTION
**Pull request by asrvd**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- changed color schemes of elements from black to t3-purple
- added hover effects on nav bar (also the active element is highlighted now)
- fixed a theme toggling issue (confirmed by nexxel on windows only)
- fixed padding for search bar in mobile nav bar
- changed scrollbar thumb color for dark mode in leftSideBar

---

## Screenshots

image
image

💯

### CODE REVIEW

**Comment by asrvd** [comment]
leaving the pr on draft for now as ill add some more changes

**Comment by asrvd** [comment]
i think its ready for a review now, new changes -

- global scrollbar changed ( the default one was ugly )
image

- toggle button changes icon on click now

https://user-images.githubusercontent.com/68690233/193561436-bd20740d-3087-4557-9add-ecbcf190a57a.mp4

**Review by nexxeln — COMMENTED** [review]
Is it just me or are these colors different?
image

image

**Comment by asrvd** [comment]
uh yes i think the sidebar has the 200 variant

**Comment by asrvd** [comment]
- fixed font sizes on mobile
- fixed some padding issues

**Review by nexxeln — APPROVED** [review]
I like it

**Comment by c-ehrlich** [comment]
It's looking really good! 

Since iPhone 8 is basically the smallest size we need to care about anymore, I think the page could even have a bit more spacing than it currently does. However I think it's also fine the way it is now. I don't know of an init tool with a better looking website :)

Screenshots for reference:

iPhone 8 size
image

iPhone 14 size (similar to or a bit smaller than most android devices)
image

**Comment by nexxeln** [comment]
Conflicts @asrvd

**Comment by asrvd** [comment]
i dont have my laptop with me atm, will do it tmrw

**Comment by asrvd** [comment]
ready to get merged @nexxeln 👍🏼

**Comment by asrvd** [comment]
it's ready but I wanted to adjust the copy button icon size too, im getting a weird error while running dev server though

**Comment by juliusmarminge** [comment]
Ship it. You can always submit a new PR with more improvements :)

**Pull request merged**
