### PR TITLE
docs: fix theo's broken image

### PR DESCRIPTION
**Pull request by AnilSeervi**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

fix theo's broken image on `typescript` page

---

## Screenshots

| before | after |
| --- | --- |
| image | image |
_[Screenshots]_

💯

### CODE REVIEW

**Review by nexxeln — CHANGES_REQUESTED** [review]
I would prefer we just download that image and put it in the public folder. Using the image from his website will make his vercel bandwith go crazy.

**Comment by AnilSeervi** [comment]
> I would prefer we just download that image and put it in the public folder. Using the image from his website will make his vercel bandwith go crazy.

Lol, makes sense.

**Review by nexxeln — CHANGES_REQUESTED** [review]
webp maybe? 11.3 kb is a lot

**Comment by AnilSeervi** [comment]
> webp maybe? 11.3 kb is a lot

sure.

**Review by nexxeln — APPROVED** [review]

**Pull request merged**
