### PR TITLE
fix: missing next-auth types

### LINKED ISSUE #254: Adding "paths" and "baseUrl" to `tsconfig.json` breaks module augmentations
**Describe the bug**
It seems like the declared `next-auth.d.ts` is overriding the initial `next-auth` types instead of augmenting them.

**To Reproduce**

1. `pnpm dlx create-t3-app@next`
2. Select all packages
3. See `src/pages/api/auth/[...nextauth].ts` file

**Expected behavior**

Having default `next-auth` types PLUS the augmented ones.

**Screenshots**

image

image

### PR DESCRIPTION
**Pull request by zomars**
# Fixes missing type in `next-auth` module augmentation.

- [x] I reviewed linter warnings + errors, resolved formatting, types and other issues related to my work
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

fixes #254 Fixes missing type in `next-auth` module augmentation.

---

## Screenshots

_[Screenshots]_

image

### CODE REVIEW

**Comment by nexxeln** [comment]
I'm unable to reproduce the bug, let's talk in the issue first

**Review by nexxeln — COMMENTED** [review]
Thanks, are you sure `next-auth/core/types` is the correct file?

**Comment by nexxeln** [comment]
Just checked the `next-auth` repo, looks good.

**Review by nexxeln — APPROVED** [review]

**Comment by zomars** [comment]
> Thanks, are you sure `next-auth/core/types` is the correct file?

yup 

image


image

**Pull request merged**
