### PR TITLE
fix: docs css issues

### PR DESCRIPTION
**Pull request by c-ehrlich**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Fix a bunch of CSS stuff in the docs
- table of contents having visible li marker bullet points at some sizes
- table of contents disappearing at sm
- content being too narrow at sm
- menu not taking full width at sm
- menu text being smaller at sm than xs

edit: the spacing diff on css was done by prettier, lmk if you prefer to keep the tabs and i'll undo it

💯

### CODE REVIEW

**Comment by c-ehrlich** [comment]
the spacing diff on css was done by prettier, lmk if you prefer to keep the tabs and i'll undo it

**Comment by juliusmarminge** [comment]
hold on i'm doing some major refactoring in my pr that will probably conflict.

would you mind PRing into the `julius/docs-theming` branch?

**Comment by c-ehrlich** [comment]
> hold on i'm doing some major refactoring in my pr that will probably conflict.
> 
> I repointed the PR to `julius/docs-theming` branch, would you mind resolving the conflicts?

probably wont have time to get to it before tomorrow evening. let me know if the stuff you're working on has hit main, otherwise i'll rebase on top of docs-theming

**Review by juliusmarminge — COMMENTED** [review]
i applied these changed on my branch

**Pull request closed without merging**
