### PR TITLE
docs: use optimized webp image for ts thumbnail

### PR DESCRIPTION
**Pull request by linaseervi**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog
use optimized webp image for ts thumbnail
_[Short description of what has changed]_

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Can you not use the Image component and get optimizations based on screen size?

**Comment by linaseervi** [comment]
> Can you not use the Image component and get optimizations based on screen size?

It is possible, with a bit more work.
read - https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by juliusmarminge** [comment]
Hey, we just feature-locked main and switched `next` to the default branch. Please resolve any conflicts in this PR that may have occurred from the switch

**Comment by linaseervi** [comment]
Opened #607 and close this due to a lot of merge conflicts.

**Pull request closed without merging**
