### PR TITLE
feat: add prompt to use trpc10

### PR DESCRIPTION
**Pull request by juliusmarminge**
# Add option to scaffold with tRPC v10

- [x] I reviewed linter warnings + errors, resolved formatting, types and other issues related to my work
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

Now that tRPC is sort of stable and got a lot of attention on stream, I thought it would be a good idea to add the ability to scaffold a project using tRPC v10.

As it is still in Alpha, and the API of v10 is not yet finalized, the option to scaffold with v9 is still there as the default, but if people want to use v10 there is now the option to select that via an additional prompt.

See a fully-stacked example app here: [juliusmarminge/t3-starters/trpc10-full](https://github.com/juliusmarminge/t3-starters/tree/main/trpc10-full). It includes all packages. 

For a more minimal example, check out this repo: [juliusmarminge/t3-starters/trpc10-minimal](https://github.com/juliusmarminge/t3-starters/tree/main/trpc10-minimal). It is scaffolded with only trpc10.

---

## Screenshots

Here is a showcase of the scaffolding process:
CleanShot 2022-07-14 at 22 36 18

### CODE REVIEW

**Comment by nexxeln** [comment]
I'm not too sure about how v10 is set up so are you sure this is the right config?

**Comment by juliusmarminge** [comment]
> I'm not too sure about how v10 is set up so are you sure this is the right config?

You mean like folder structure way or? This got all the correct pieces and it follows the same parterns that i used when migrating the tRPC examples over there.

Question is if we include this as a prompt or release create-t3-app@next similar to how tRPC does?

**Comment by nexxeln** [comment]
> Question is if we include this as a prompt or release create-t3-app@next similar to how tRPC does?

Sounds good to me

**Comment by ninox14** [comment]
i've had an issue when installing packages in generated with this branch 
[`issue with screenshots on trpc repo`](https://github.com/trpc/trpc/issues/2216)

basically it generates `package.json` with wrong names for v10 trpc 
```json
    "@trpc/server@experimental": "^10.0.0-alpha.38",
    "@trpc/client@experimental": "^10.0.0-alpha.38",
    "@trpc/next@experimental": "^10.0.0-alpha.38",
    "@trpc/react@experimental": "^10.0.0-alpha.38"
```

removing `@experimental` from package names solves this issue

**Comment by juliusmarminge** [comment]
> basically it generates package.json with wrong names for v10 trpc

this seems to be resolved on trpc's end or at least it doesn't happen on my end when i tested now..

> > Question is if we include this as a prompt or release create-t3-app@next similar to how tRPC does?

> Sounds good to me

Closing this and opened up #203

**Pull request closed without merging**
