### PR TITLE
fix: folder structure list elements now properly disappear when deselected

### LINKED ISSUE #984: bug(docs): filtered folders still shows up in ToC
We might want to hide elements from the TOC that's not actually displayed:

CleanShot 2022-12-15 at 23 44 55

_Originally posted by @juliusmarminge in https://github.com/t3-oss/create-t3-app/issues/963#issuecomment-1353811622_

### PR DESCRIPTION
**Pull request by benmarg**
Solves #984

## ✅ Checklist

- [X] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [X] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] I performed a functional test on my final commit

---

## Changelog

Folder structure in side bar now properly disappear when their corresponding category is deselected in the main Folder Structure component. 

---

## Screenshots

💯

### CODE REVIEW

**Comment by benmarg** [comment]
This doesn't fix the "last option never gets highlighted bug" I mentioned on the issue thread( #984 ). I can either add it this PR I'm able to fix it tomorrow, otherwise I can open a new issue if you'd like to keep them separate!

**Review by juliusmarminge — CHANGES_REQUESTED** [review]
While this does seem to work right now, I'd like to have it a bit more decoupled from the ToC itself. Having these strings hardcoded in here seems like begging for bugs down the road when we add a file or something and need to go into multiple places.

Can we either:
1. grab the files from the tree-configuration itself so that becomes the source of truth
2. Get the heading in the actual FolderStructure component and hide each heading there?

We also need this logic in the `On this page` component which is used on mobile

**Comment by benmarg** [comment]
The thought crossed my mind of making the solution more upstream, but I ended up implementing this as it was the simplest solution at the time. I'll look closer at the solutions you proposed later tonight and try to implement them!

**Comment by juliusmarminge** [comment]
> The thought crossed my mind of making the solution more upstream, but I ended up implementing this as it was the simplest solution at the time. I'll look closer at the solutions you proposed later tonight and try to implement them!

I could also merge this for now as it works and just keep the issue open if anyone wants to go in and refactor it to a more automatic approach?

**Comment by benmarg** [comment]
Ya that seems like a good solution for now! Sorry I haven't had time to do the refactor as of yet.

**Review by juliusmarminge — APPROVED** [review]

**Comment by juliusmarminge** [comment]
Thanks for the PR 🙏🏼. Feel free to keep working on it in a new PR if you're down. I left the issue opened and gave a brief description of what's left

**Pull request merged**
