### PR TITLE
docs: fix typo in prisma.md should be "a" instead of "an"

### PR DESCRIPTION
**Pull request by bill-li1**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by c-ehrlich** [comment]
Is it called ess-q-lite or see-quel-lite?

**Comment by juliusmarminge** [comment]
@AyanavaKarmakar

**Comment by AyanavaKarmakar** [comment]
The internet seems to have polarizing opinions on the pronunciation of `SQL`.

However, `an` seems to be **"correct"** if we go by the [ISO/IEC](https://www.iso.org/standard/53681.html) site.

image

image

Also, refer: https://database.guide/is-it-pronounced-s-q-l-or-sequel/

@c-ehrlich @bill-li1

**Comment by AyanavaKarmakar** [comment]
Looks SQLite [docs](https://www.sqlite.org/whentouse.html) itself uses `an`. 

image

**Comment by juliusmarminge** [comment]
> Looks like SQLite [docs](https://www.sqlite.org/whentouse.html) itself uses `an`.
> 
> image

Then we keep the `an`

**Pull request closed without merging**
