### PR TITLE
fix(templates): h1 restored

### PR DESCRIPTION
**Pull request by mnik01**
When added UI changes to templates h1 tags was removed  😆

see https://github.com/t3-oss/create-t3-app/pull/115

### CODE REVIEW

**Comment by mnik01** [comment]
Opened this PR to main cause dev on that moment does not have changes from 
https://github.com/t3-oss/create-t3-app/pull/115

**Comment by mnik01** [comment]
> Opened this PR to main cause dev on that moment does not have changes from #115

Changed target to dev. Cause now it cause this changes

**Comment by Dhravya** [comment]
Looks good to me~

**Comment by asheeeshh** [comment]
i don't think it will make any difference as the font size remains the same.

**Comment by nexxeln** [comment]
This is good semantics, thank you!

**Pull request merged**
