### PR TITLE
fix(next-auth): Prisma Model update for next-auth

### PR DESCRIPTION
**Pull request by KubaRocks**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Default `next-auth` with `prisma` setup doesn't work with GitHub OAuth and according to [this issue](https://github.com/nextauthjs/next-auth/issues/3465) probably with some others providers too.
Updated model fixes the issue.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
See #182. We switched to Discord as default since Github is a bit special in that it requires more setup.

**Comment by KubaRocks** [comment]
According to issue I've linked, this also fixes issues with Facebook and Google (although I didn't test it).
If the goal is to stay with default schema that next-auth provides in their docs, then we can close that PR.
Although it would be cool to mention this issue somewhere, so the newcomers are not confused.

From my perspective - schema currently has some excessive nullable fields to fulfill variety of different auth scenarios. Adding this 3 fields helps OTB integrating other providers without need of researching why auth is failing.
Small cost comparing to improved usability.

**Comment by juliusmarminge** [comment]
I cant see anything of this field being provided by Facebook or Google on the documentation: https://next-auth.js.org/providers/

Every provider provides a bit different fields, and I'm afraid if we start doing special treatments for one, people are going to wonder why we haven't done so for another.

**Comment by nexxeln** [comment]
I think discord is fine, not too keen on merging this. We want to be as close to the official docs as possible.

**Review by nexxeln — COMMENTED** [review]
I think discord is fine, not too keen on merging this. We want to be as close to the official docs as possible.

**Comment by juliusmarminge** [comment]
We can probably include a few words about this and refer to the appropriate docs in our upcoming docs page, but we shouldn't include it by default

**Pull request closed without merging**
