### PR TITLE
feat: add continue and overwrite option on existing dir

### PR DESCRIPTION
**Pull request by c-ehrlich**
Closes https://github.com/t3-oss/create-t3-app/issues/230

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Add another choice to the CLI if there are existing files: continue and overwrite

---

## Screenshots

CLI Option:
Screenshot 2022-08-29 at 21 37 54

Each choice:
Screenshot 2022-08-29 at 21 37 38
Screenshot 2022-08-29 at 21 38 19
Screenshot 2022-08-29 at 21 41 03

Scaffolding dir before running CLI (and after aborting):
Screenshot 2022-08-29 at 21 40 03

Scaffolding dir after emptying the folder:
Screenshot 2022-08-29 at 21 41 26

Scaffolding dir after continue and overwriting (package.json is overwritten, `somefile` still exists):
Screenshot 2022-08-29 at 21 40 27

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
You think it would be overkill to add a verification step when choosing overwrite or empty? And maybe tagging cancel as "recommended"?

**Comment by c-ehrlich** [comment]
> You think it would be overkill to add a verification step when choosing overwrite or empty? And maybe tagging cancel as "recommended"?

Sure, can implement those :)

**Comment by juliusmarminge** [comment]
> > You think it would be overkill to add a verification step when choosing overwrite or empty? And maybe tagging cancel as "recommended"?
> 
> Sure, can implement those :)

from experience, better be safe than sorry before deleting files 😄

**Comment by c-ehrlich** [comment]
image

**Review by juliusmarminge — APPROVED** [review]
👍🏼

**Comment by juliusmarminge** [comment]
The new jobs which hasn't run yet is from my PR. Don't worry bout those

**Pull request merged**
