### PR TITLE
feat: add logs during dev

### PR DESCRIPTION
**Pull request by Gejsi**
# Add loggers during development

- [x] I reviewed linter warnings + errors, resolved formatting, types and other issues related to my work
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

Ref #306, ref #296
- [x] Dismantle prisma client on `teardown`
- [x] Add prisma logs
- [x] Add tRPC logs 

---

## Screenshots
Example prisma logs:
image

Example tRPC logs:
image

💯

### CODE REVIEW

**Comment by Gejsi** [comment]
For checkbox n1, I had to create a separate file called `api-handler-prisma.ts`, because putting the 1-liner
inside `api-handler.ts` would also add the line for users that don't use prisma.

Commit c4ffe36 fixes an incorrect query I found while testing some stuff out.

For checkbox n2: the prisma middleware has a small caveat, the amount of the same logs increases in a weird way due to HMR.
For example, the query shown in the screenshot, after **three** hot reloads becomes:
```
prisma:query [...]
Query Exampe.findMany took 21ms
Query Exampe.findMany took 21ms
Query Exampe.findMany took 21ms
```
But, it's not really deterministic (sometimes 3 hot reloads only cause a duplicate). So I decided to comment it out, instead of having it on by default.

For checkbox n3: the tRPC logger works only if `httpBatchLink` or `httpLink` are present in the config. Since batching is the default, I've put `httpBatchLink` explicitly.
A smarter approach could be taken by [enabling or disabling batching for certain requests](https://trpc.io/docs/links#using-a-splitlink-to-control-request-flow).
Having something like:
```ts
splitLink({
  condition({ context }) {
    // check for context property `includeBatch`
    return context.includeBatch === true
  },
  // when condition is true, use batching...
  true: httpBatchLink({ url, maxBatchSize: 10 }),
  // ...otherwise use normal requests
  false: httpLink({ url }),
}),
```
Batching requests for two queries:
```ts
const firstQuery = trpc.useQuery(['example.hello'], {
  context: {
    includeBatch: true
  }
})
const secondQuery = trpc.useQuery(['example.getAll'], {
  context: {
    includeBatch: true
  }
})
```
One issue with this approach is that tRPC doesn't currently offer a _strict_ typesafety for the `context` object (e.g. no autocomplete for `context.includeBatch`), but this could be solved by extending the type definition in a `foo.d.ts` file.

**Comment by juliusmarminge** [comment]
We have migrated the repo into a monorepo with the website baked in. All CLI stuff now goes into [`cli`](https://github.com/t3-oss/create-t3-app/tree/main/cli)

**Comment by Gejsi** [comment]
Any review progress for this PR @TheoBr?
There are conflicts between the branches, @juliusmarminge how should I resolve them in this case?

**Comment by juliusmarminge** [comment]
Sorry om travelling foot so not much time for coding. I'll try to look it over tonight.

As for the conflicts, just resolve so that they are made to cli/src instead of src

**Comment by Gejsi** [comment]
> As for the conflicts, just resolve so that they are made to cli/src instead of src, or cli/template instead of template etc

Ok.
I noticed that PR #330 fixes the stuff that I already fixed in a slightly different way in commit c4ffe36.
If the two PRs get merged together the project would still be broken.
So I either revert my commit or that PR should be closed without merging.

**Comment by juliusmarminge** [comment]
> > As for the conflicts, just resolve so that they are made to cli/src instead of src, or cli/template instead of template etc
> 
> 
> 
> Ok.
> 
> I noticed that PR #330 fixes the stuff that I already fixed in a slightly different way in commit c4ffe36.
> 
> If the two PRs get merged together the project would still be broken.
> 
> So I either revert my commit or that PR should be closed without merging.

I prefer nex's solution with renaming the actual router, so you can revert that specific change on your PR 👍

**Comment by juliusmarminge** [comment]
Will you fix the conflicts?

When you are at it, point the PR to `next`. tRPC 10 is coming closer and closer to release so I think it's better we push new features there?

**Comment by Gejsi** [comment]
Tbh, I haven't been working on it since I was waiting for the review: there are still some decisions to be made and I didn't want to add features that would just be deleted.
With that said, I will fix the conflicts soon, should I create a new PR only for the `next` version?
Because theo's review isn't coming, what's your opinion on the first comment I made @juliusmarminge (logger caveat, batching...)?

**Comment by juliusmarminge** [comment]
Oh sorry...

I redid the loggerLink on next #352, but more than happy to let you submit a new PR doing just that so that you'll be credited accordingly 😄 

I think the explicit batchLink is required, but we don't need to overwrite the default batchSize so we should stick to the default on that

**Comment by Gejsi** [comment]
No worries, I will close this PR and open a new one for the `next` branch.
If you want to close your PR it's fine with me because I can redo that :+1:

**Comment by juliusmarminge** [comment]
Make yours and I'll close and link them

**Comment by Gejsi** [comment]
I cannot open PRs to the `next` branch because I'm not a member.
Maybe, I can make open a simple PR to `main` with the trpc v9 stuff and you will re-add them from your new PR to `next`?

**Comment by juliusmarminge** [comment]
> I cannot open PRs to the `next` branch because I'm not a member.
> 
> Maybe, I can make open a simple PR to `main` with the trpc v9 stuff and you will re-add them from your new PR to `next`?

FR? Yea just make to main then. Sorry for the troubles

**Pull request closed without merging**
