### PR TITLE
feat: added light mode back

### PR DESCRIPTION
**Pull request by gabrielelpidio**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Addresses [#440](https://github.com/t3-oss/create-t3-app/issues/440)
- Fixed toggle initialization
- Fixed scrollbar on light mode
- Fixed code background on light mode
- Added darker color for hover on sidebar links

---

## Screenshots

image

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Seems to be some bug on mobile introduced where the page has some space to the right?

image

I also think we should have lightmode codeblocks, Ideally we dont need to do all this ourself but just use some tool that lets us use VSCode themes or something? I know `shiki` has this.

**Comment by gabrielelpidio** [comment]
Shiki is the [default](https://docs.astro.build/en/reference/configuration-reference/#markdownshikiconfig) syntax highlighter in astro. Adding a theme should be as easy as:
```js
export default defineConfig({
  // ...config
  markdown: {
    shikiConfig: {
      theme: "poimandres",
    },
  },
})
```
on `astro.config.mjs`

but having multiple syntax highlighting for dark and light mode doesn't seem to be totally resolved at the time of writing: 
Check out: https://github.com/shikijs/shiki/issues/33

So we could either use "css-variables" as the theme and pass some variables or just use something like the `poimandres` which looks relatively good on both light and dark mode

For reference
image

Also think full width code blocks look much better

image

Also Updated the PR with the recoommendations mentioned above

**Review by juliusmarminge — APPROVED** [review]
Awesome.

**Review by kroucher — APPROVED** [review]
Love it, awesome work @gabrielelpidio!

**Pull request merged**
