### PR TITLE
docs: add new project to the collection list

### PR DESCRIPTION
**Pull request by Moltivie**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by nexxeln** [comment]
Please run `pnpm format`

**Comment by Moltivie** [comment]
@nexxeln that should be fixed!

**Comment by Moltivie** [comment]
I managed to push it into the `main` branch. Is it still good or I have to PR it to the `next` one?

**Comment by AyanavaKarmakar** [comment]
> I managed to push it into the `main` branch. Is it still good or I have to PR it to the `next` one?

`main` branch is no longer maintained and should only get critical bug fixes. Please submit your PRs to the next branch.

**Comment by Moltivie** [comment]
Ok. I will close this commit and re-open it on the correct branch.

**Pull request closed without merging**
