### PR TITLE
docs: make scrollbar show on right in RTL

### PR DESCRIPTION
**Pull request by AyanavaKarmakar**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Refer: #1002 

image

- Before

image

- After

image

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Why should it be on the right? The main scrollbar is on the left, no?

**Comment by AyanavaKarmakar** [comment]
> Why should it be on the right? The main scrollbar is on the left, no?

All the scrollbars are on the right in RTL like in LTR. Shouldn't the language selector also be on the right, like @c-ehrlich said?

image

**Comment by juliusmarminge** [comment]
Oh my bad then. I thought they were on the left but must have remembered wrong.

**Comment by c-ehrlich** [comment]
> Oh my bad then. I thought they were on the left but must have remembered wrong.
> 
> Are we doing something custom here then? Or why doesnt the browser handle this correctly?

Scrollbars on the right side in RTL seems to be standard as far as I can tell. Here's an example from the React docs. It seems they are using the same "hack" of switching the container that has the scrollbar to LTR, and then the stuff inside it back to RTL.

image

As to why browsers don't do this if it's the "standard", no idea.

**Comment by Sboonny** [comment]
image

> All the scrollbars are on the right in RTL like in LTR. Shouldn't the language selector also be on the right

I think this is caused by confusion. Scroll bars are on the right in RTL. We are used to it there because of Google and Facebook positioning them there

**Review by c-ehrlich — COMMENTED** [review]
lets get this merged :)

**Review by c-ehrlich — APPROVED** [review]

**Pull request merged**
