### PR TITLE
docs: fix layout

### PR DESCRIPTION
**Pull request by c-ehrlich**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- fixes docs layout at all screen sizes
- fixes weird layout shift on everything that was introduced in a recent pr
- simplifies the dom quite a bit

---

## Screenshots

- no screenshots, you should use the test deployment and see if the layout is broken at some sizes or not

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
image

Eeerhm something weird's going on

**Comment by c-ehrlich** [comment]
🤬
will try to reproduce/fix tomorrow
i also noticed a new issue when opening the hamburger menu on the landing page

**Comment by c-ehrlich** [comment]
> Eeerhm something weird's going on
figured this one out, it was safari not respecting h-full 🫥

**Comment by c-ehrlich** [comment]
Can't figure out how to set to draft on my phone, but please don't merge yet. Found one more issue (ToC overflows the bottom of the screen on mobile)

**Comment by juliusmarminge** [comment]
Is this what you're trying to fix?

https://user-images.githubusercontent.com/51714798/201400658-87e49194-aaad-412d-bff1-f168d7a922f4.MOV

**Comment by c-ehrlich** [comment]
It's working for me now in mobile safari. Do you still have this big on your phone?

https://user-images.githubusercontent.com/8353666/201401853-b808197e-146f-4f28-be98-a6c037c29678.MOV

**Comment by juliusmarminge** [comment]
Search button is cut off in docs pages;

image

Put bg on nav for mobile?

image

**Comment by juliusmarminge** [comment]
> It's working for me now in mobile safari. Do you still have this big on your phone?

Yep that's fixed 👌👌

**Comment by juliusmarminge** [comment]
Now it's just on the entire left navbar, not the "nav" 

image

**Comment by juliusmarminge** [comment]
Sorry, I must be annoying but the search bar isn't centered 😜

image

**Comment by AyanavaKarmakar** [comment]
Hey, not sure if you've noticed these issues yet and are already working on a fix.

DesktopView

MobileView


Also, the `T3 Collection` button is gone.

**Comment by AyanavaKarmakar** [comment]
nit: `Other Recommendations` looks dangerously/uncomfortably close to the scrollbar

image

Previously:

image

**Comment by c-ehrlich** [comment]
note to self: custom scrollbar behavior is completely broken in firefox (on macos) - but same is true on beta.create.t3.gg

**Comment by c-ehrlich** [comment]
> Also, the `T3 Collection` button is gone.

This is on purpose - the navbar is already cramped at md

image

**Comment by c-ehrlich** [comment]
image
we were putting `break-all` on every li in markdown, i changed it to only be on `<code>` elements

**Comment by nexxeln** [comment]
This looks good on my end, tested on a 14 inch laptop and galaxy s9+

**Review by juliusmarminge — APPROVED** [review]
All good I think.

Scrollbar missing on Firefox (as of #723) but not sure why??

**Comment by juliusmarminge** [comment]
uurgh this layout shift is kinda bad https://share.cleanshot.com/ci5v6j

**Comment by nexxeln** [comment]
We can cache the font once it has loaded. I'll push a commit wait

**Comment by nexxeln** [comment]
Better I think https://this-vegetable.is-from.space/brave_bK9eDEMC0o.mp4

**Comment by c-ehrlich** [comment]
Also fixed the other pop-in issue on the landing page

Before:
https://user-images.githubusercontent.com/8353666/201514798-f2ea9658-52b8-4782-9272-04b12c1db015.mov

After
https://user-images.githubusercontent.com/8353666/201514802-fdc7e00d-9b8c-4bce-bc83-4463537462cd.mov

**Comment by c-ehrlich** [comment]
right sidebar icon alignment

before:
image

after:
image

**Comment by c-ehrlich** [comment]
Aligned Navbar vertically with the stuff below it at md and above. xs/sm is unchanged.

Before:
Screenshot 2022-11-13 at 10 41 17

After:
Screenshot 2022-11-13 at 10 41 02

**Comment by juliusmarminge** [comment]
We good to merge?

**Comment by c-ehrlich** [comment]
> We good to merge?

i think so.

there's many things left to improve of course, but this pr is already bigger than it should be

**Pull request merged**
