### PR TITLE
feat: cursor-pointer on theme toggle button

### PR DESCRIPTION
**Pull request by c-ehrlich**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Theme toggle button used a plain mouse cursor before, changed it to pointer

💯

### CODE REVIEW

**Review by nexxeln — APPROVED** [review]

**Comment by nexxeln** [comment]
Should we install clsx or something?

**Comment by c-ehrlich** [comment]
> Should we install clsx or something?

seems like a good idea, there will sooner or later be a situation where we will need it even more than this

i have no idea about which is better between classnames vs clsx, any preference?

**Comment by nexxeln** [comment]
> 

They're both the same basically, I prefer clsx but you can install whatever you want.

**Comment by juliusmarminge** [comment]
Trying to get this lighthouse thing to work grrr.

**Comment by juliusmarminge** [comment]
Sorry for littering your PR xD

**Review by nexxeln — APPROVED** [review]

**Pull request merged**
