### PR TITLE
ci: :zap: Add /cli change validation to CI workflow

### PR DESCRIPTION
**Pull request by Jacksonmills**
Should allow for changes to www and docs to be free from ci errors around changeset, I have little exp working with the ci but thought I would try my attempt at a fix!

Closes [#1623](https://github.com/t3-oss/create-t3-app/issues/1623)

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I pushed a series of commits specifically designed to trigger various edge cases in the GitHub CI workflow, ensuring comprehensive functional testing of the entire process.

---

## Changelog

Added a new step in the CI workflow to check for changes in the /cli directory. If there are any changes, it will validate the changeset by running `pnpm changeset status --since origin/next`. This ensures that changes made to /cli are properly tracked and validated.

💯⚡

### CODE REVIEW

**Comment by Jacksonmills** [comment]
image

noice

**Comment by c-ehrlich** [comment]
thanks for picking this up! the current version seems to hit false negatives, see https://github.com/t3-oss/create-t3-app/pull/1626

also @juliusmarminge do we also need to include a few files in root such as eslintrc, prettier config, etc? i'm leaning no, because none of them should change the ux of using the cli

**Comment by Jacksonmills** [comment]
> thanks for picking this up! the current version seems to hit false negatives, see https://github.com/t3-oss/create-t3-app/pull/1626
> 
> also @juliusmarminge do we also need to include a few files in root such as eslintrc, prettier config, etc? i'm leaning no, because none of them should change the ux of using the cli

Ah okay thanks for adding the test PR, I'll see what's going on with that

**Comment by Jacksonmills** [comment]
> thanks for picking this up! the current version seems to hit false negatives, see #1626
> 
> also @juliusmarminge do we also need to include a few files in root such as eslintrc, prettier config, etc? i'm leaning no, because none of them should change the ux of using the cli

@c-ehrlich I think I got it working if you would like to pull my changes and test for yourself. I was able to fail and pass with and without a change in cli/src/index.ts

**Comment by Jacksonmills** [comment]
Okay in my testing it fails when no changeset + change in `ci/src/index.ts` and passes when you add changeset or remove the change from `ci/src/index.ts`

**Comment by Jacksonmills** [comment]
Gonna come back to this tomorrow ...

**Comment by Jacksonmills** [comment]
Running all the tests ... but it seems the grep command was the culprit, needed to return true if grep doesn't find any matches, allowing the script to proceed to the else block gracefully.

**Review by c-ehrlich — APPROVED** [review]
working great now. thanks so much for adding this!

**Pull request merged**
