### PR TITLE
docs: increase the contrast of navigation links' text color against the background color. 

### LINKED ISSUE #720: docs: make navigation link colors in light mode contrast more against the background.
### Is your feature request related to a problem? Please describe.

Currently, the color contrast of dark mode's anchor tags against the background is significantly better than light mode's. This may be an accessibility issue for some people.

Screen Shot 2022-11-11 at 9 48 49 PM

### Describe the solution you'd like to see

Update the text color from `text-t3-purple-400` to `text-t3-purple-800`. 

Screen Shot 2022-11-11 at 9 50 02 PM

### Describe alternate solutions

Alternatively, update the text color to a darker shade that fits the color scheme better.

### Additional information

Submitted a PR (#722) for your review since this is a small change.

### PR DESCRIPTION
**Pull request by vlmlee**
Closes #720

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

* Updated the text color of the left navigation links from `text-t3-purple-400` to `text-t3-purple-800`. 
* Updated the text color of the top navigation links from `text-t3-purple-500` to `text-t3-purple-800` and its `:hover` pseudo-class from `hover:text-t3-purple-800` to `hover:text-t3-purple-400`. This is just for consistency. 
* Updated the text color of `Table of Contents` from `text-t3-purple-500` to `text-t3-purple-800` and its `:hover` pseudo-class from `hover:text-t3-purple-800` to `hover:text-t3-purple-400`.
* Updated the text color of `More` from `text-t3-purple-500` to `text-t3-purple-800` and its `:hover` pseudo-class from `hover:text-t3-purple-800` to `hover:text-t3-purple-400`.

---

## Screenshots

Before:
Screen Shot 2022-11-11 at 10 03 22 PM

After:
Screen Shot 2022-11-11 at 10 22 47 PM

💯

### CODE REVIEW

**Review by nexxeln — APPROVED** [review]
Much better

**Comment by asrvd** [comment]
can we make the bg-color bit more dull for light mode, now that we're at it

**Comment by vlmlee** [comment]
> can we make the bg-color bit more dull for light mode, now that we're at it

good suggestion

**Comment by vlmlee** [comment]
before:
Screen Shot 2022-11-11 at 10 22 47 PM

after:
Screen Shot 2022-11-12 at 12 21 41 AM

**Comment by nexxeln** [comment]
I liked the old one more to be honest.

**Comment by vlmlee** [comment]
I can revert it with no problem.

**Comment by asrvd** [comment]
> > can we make the bg-color bit more dull for light mode, now that we're at it
> 
> good suggestion, does the color have a particular name? I can just try making it 10% lighter as 20% lighter will make it white.

oh lol, I didnt mean "lighter", by dull I mean make the color more off-white

**Comment by vlmlee** [comment]
> > > can we make the bg-color bit more dull for light mode, now that we're at it
> > 
> > 
> > good suggestion, does the color have a particular name? I can just try making it 10% lighter as 20% lighter will make it white.
> 
> oh lol, I didnt mean "lighter", by dull I mean make the color more off-white

Ah, meaning not pink, more grey? You'll have to let me visualize it with a few color swatches.

**Comment by asrvd** [comment]
how does (219, 199, 219) look

**Comment by asrvd** [comment]
image

this one is `rgb(219, 208, 219)`, looks good to me but we'll have to adjust the navbar font color a bit

**Comment by asrvd** [comment]
@nexxeln ^

**Comment by nexxeln** [comment]
> @nexxeln ^

I need to see a deployed version

**Comment by c-ehrlich** [comment]
Out of the screenshots I actually like the current bg color the most, but agree I would have to see it deployed to really know.

One nitpick: the selected item in the navbar ("Docs") is still really low contrast. Maybe make the bg-color a bit darker, and the text the same color as the non-selected item next to it?

image

**Comment by vlmlee** [comment]
> Out of the screenshots I actually like the current bg color the most, but agree I would have to see it deployed to really know.
> 
> One nitpick: the selected item in the navbar ("Docs") is still really low contrast. Maybe make the bg-color a bit darker, and the text the same color as the non-selected item next to it?
> 
> image

Yeah, I should adjust this also since I adjusted the other text colors.

**Comment by juliusmarminge** [comment]
> > Out of the screenshots I actually like the current bg color the most, but agree I would have to see it deployed to really know.
> > One nitpick: the selected item in the navbar ("Docs") is still really low contrast. Maybe make the bg-color a bit darker, and the text the same color as the non-selected item next to it?
> > image
> 
> Yeah, I should adjust this also since I adjusted the other text colors.

I'm doing some finishing touches on #714 and can take care of that there too :)

**Pull request merged**
