### PR TITLE
fix: layout shift on docs

### LINKED ISSUE #738: bug: layout shift on docs
### Provide environment information

chrome on macos

### Describe the bug

There is layout shift on the docs (look at the navbar)

I believe this was introduced in a recent PR

https://user-images.githubusercontent.com/8353666/202033226-588be4b3-8003-4106-8470-7e70f49e3f3d.mov

### To reproduce

go on the homepage, click between docs and faq

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by itswil**
Closes #738

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog
Prevent applying of global transitions
Remove transition duration for Theme Toggle

---

## Screenshots
Before:
https://user-images.githubusercontent.com/3381481/202189087-f8749ba9-b495-475d-a5aa-45a96d76ad31.mp4

After:
https://user-images.githubusercontent.com/3381481/202189122-f3705922-c9f7-4067-bef2-c20e48eb18b1.mp4

## Comments
I could only replicate the issue seen on the [Docs](https://beta.create.t3.gg/en/introduction) when running `pnpm build` and `pnpm preview` from `/www`
For reasons beyond my small brain, I could not replicate with `pnpm build:www` running from root.

💯

### CODE REVIEW

**Review by nexxeln — CHANGES_REQUESTED** [review]
Revert back to the old one because we need the transition on theme toggle

**Comment by nexxeln** [comment]
janky theme toggle

this is how it looks without the transition

**Comment by itswil** [comment]
Oops, yep
I've changed it to use `transition-colors` instead; unless theres other transitions on `body` that I'm missing context on

**Comment by juliusmarminge** [comment]
There's still flashing
CleanShot 2022-11-16 at 15 23 08

**Comment by nexxeln** [comment]
> There's still flashing

 Yeah of course cause its not an SPA

**Comment by juliusmarminge** [comment]
> > There's still flashing
> 
> Yeah of course cause its not an SPA. It's not shifting though which is a good thing

the theme toggle and navelements doesn't flash like that on the prod versino

**Comment by juliusmarminge** [comment]
Prod:

**Comment by nexxeln** [comment]
Oh interesting. I guess we have to choose between layout shifting and flashing

**Comment by juliusmarminge** [comment]
Flashing can prob be fixed later, its less annoying than the layout shift so this is good for now

**Pull request merged**
