### PR TITLE
chore: Replace React.FC and NextPage types with basic function syntax

### PR DESCRIPTION
**Pull request by ericshively**
Closes https://twitter.com/ccccjjjjeeee/status/1668694515484336145

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Remove React.FC usage in templates, replacing with standard function syntax

Per https://twitter.com/ccccjjjjeeee/status/1668694515484336145

---

## Screenshots

Screen Shot 2023-06-13 at 2 24 08 PM

💯

### CODE REVIEW

**Review by c-ehrlich — APPROVED** [review]
thanks :) happy this is being done by a first time contributor

**Review by c-ehrlich — CHANGES_REQUESTED** [review]
could you please add a changeset? this can be done by running `pnpm changeset` in the root of the project.

don't worry about the other CI failure, that one is on us

**Comment by ericshively** [comment]
> could you please add a changeset? this can be done by running `pnpm changeset` in the root of the project.

Oh, I was confused by the wording in Contributing.md "If your change should appear in the changelog, i.e. it changes some behavior of either the CLI or the outputted application."

I thought that meant visible user-facing changes as opposed to a syntactic change like this, which maybe wouldn't require a changeset.

**Comment by juliusmarminge** [comment]
Remove the NextPage too while you're at it.

```
export default function Home() {

}
```

is much cleaner than

```tsx
const Home: NextPage = () => {

};

export default Home;
```

and easier to browse when you immediately see the export default instead of having to scroll all the way to the bottom to see which is exporter and not

**Review by c-ehrlich — APPROVED** [review]
thanks for the contribution!

**Pull request merged**
