### PR TITLE
feat: use jetbrains mono for code

### PR DESCRIPTION
**Pull request by nexxeln**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

JetBrains Mono for codeblocks. Looks much better imo.

---

## Screenshots

image

### CODE REVIEW

**Comment by c-ehrlich** [comment]
What are we using currently, just system fonts? I can't tell the difference tbh

image

**Comment by nexxeln** [comment]
image
 vs 
 
image

**Comment by juliusmarminge** [comment]
yea its probably some system thing now then cause cje's barely differs but yours does.

ship it

**Comment by nexxeln** [comment]
> yea its probably some system thing now then cause cje's barely differs but yours does.
> 
> ship it

Approve

**Review by juliusmarminge — APPROVED** [review]

**Comment by Yevhenii-Bakhmat** [comment]
So there might be an issue in the future as Jetbrains mono supports ligatures. Oh it might NOT be an issue at all. Just letting you know
изображение

**Pull request merged**
