### PR TITLE
chore: bump next to 12.3

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #<issue>

## ✅ Checklist

- [ ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [ ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
hmm have they changed something in the AppType typedefintion?

**Comment by juliusmarminge** [comment]
> yes, seems to be some change in the typedef
> 
> ```
> ./src/pages/_app.tsx:13:16
> Type error: Property 'session' does not exist on type '{}'.
> 
>   11 | const MyApp: AppType = ({
>   12 |   Component,
> > 13 |   pageProps: { session, ...pageProps },
>      |                ^
>   14 | }) => {
>   15 |   return (
>   16 |     <SessionProvider session={session}>
> ```

ill post an issue on their side to see if this is intended

**Comment by c-ehrlich** [comment]
I believe it's related to the typedef of `AppInitialProps` having been changed from:

```ts
export declare type AppInitialProps = {
    pageProps: any;
};
```
to:
```ts
export declare type AppInitialProps<P = any> = {
    pageProps: P;
};
```

**Comment by c-ehrlich** [comment]
12.2:
```ts
export declare type AppInitialProps = {
    pageProps: any;
};
export declare type AppPropsType<R extends NextRouter = NextRouter, P = {}> = AppInitialProps & {
    Component: NextComponentType<NextPageContext, any, P>;
    router: R;
    __N_SSG?: boolean;
    __N_SSP?: boolean;
    __N_RSC?: boolean;
};
```

12.3:
```ts
export declare type AppInitialProps<P = any> = {
    pageProps: P;
};
export declare type AppPropsType<R extends NextRouter = NextRouter, P = {}> = AppInitialProps<P> & {
    Component: NextComponentType<NextPageContext, any, any>;
    router: R;
    __N_SSG?: boolean;
    __N_SSP?: boolean;
    __N_RSC?: boolean;
};
```

**Comment by juliusmarminge** [comment]
https://github.com/vercel/next.js/issues/40371

**Comment by juliusmarminge** [comment]
We'll wait until 12.3.1 is out so we can utilize the new generic AppType<P> type

**Comment by juliusmarminge** [comment]
continued in #485

**Pull request closed without merging**
