### PR TITLE
refactor: landing page improvements

### PR DESCRIPTION
**Pull request by nexxeln**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Removed 'read more' from the stack card
- Changed the order of the cards
- Made the link to init.tips better looking
---

### CODE REVIEW

**Comment by juliusmarminge** [comment]
I think the Read more with an external link icon I added yesterday was good cause it made it clear you were leaving the page, now there's no way of knowing there's even a link on the stack cards?

**Comment by nexxeln** [comment]
> I think the Read more with an external link icon I added yesterday was good cause it made it clear you were leaving the page, now there's no way of knowing there's even a link on the stack cards?

Maybe we can make the whole card a link? Idk read more looked and felt weird to me.

**Comment by juliusmarminge** [comment]
> > I think the Read more with an external link icon I added yesterday was good cause it made it clear you were leaving the page, now there's no way of knowing there's even a link on the stack cards?
> 
> 
> 
> Maybe we can make the whole card a link? Idk read more looked and felt weird to me.

Ideally the link would be more describing 🤔

**Review by juliusmarminge — COMMENTED** [review]
Cli broken on mobile again image

**Comment by nexxeln** [comment]
Closing this cause #501 has been merged.

**Comment by Coyenn** [comment]
> Closing this cause #501 has been merged.

#501 was meant as an edition to #493, hence it has been merged into your feature. So we still need to merge this branch into main.

**Comment by nexxeln** [comment]
> > Closing this cause #501 has been merged.
> 
> #501 was meant as an edition to #493, hence it has been merged into your feature. So we still need to merge this branch into main.

Missed that sorry

**Comment by juliusmarminge** [comment]
Links on cards are still weird? https://share.cleanshot.com/fXVAnk

**Comment by Coyenn** [comment]
> Links on cards are still weird? https://share.cleanshot.com/fXVAnk

Should be fixed now.

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
