### PR TITLE
feat(template): add createdAt and updatedAt to example model

### LINKED ISSUE #618: feat: Add createAt and updatedAt to the prisma models
### Is your feature request related to a problem? Please describe.

Not really. But I wanted that attribute on the User and Account models for sure. I created one without it and had to delete it and remake it!

### Describe the solution you'd like to see

It's a minor improvement, but I think it would be useful to add createdAt and updatedAt attributes to at least one of the models in the default prisma.schema. It's something that I think most people want and wont know how to do at first. At least that was the case for me. 

### Desribe alternate solutions

Just add

```
model Example {
    id        String   @id @default(cuid())
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
}
```

to Example

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by nexxeln**
Closes #618 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

Added `createdAt` and `updatedAt` to Example prisma model.

### CODE REVIEW

**Review by juliusmarminge — APPROVED** [review]

**Comment by nexxeln** [comment]
I also have to format. Don't merge before I push that commit.

**Comment by juliusmarminge** [comment]
> I also have to format. Don't merge before I push that commit.

Wow why so large diff? Sure thats the  correct formatting?

**Comment by nexxeln** [comment]
> > I also have to format. Don't merge before I push that commit.
> 
> Wow why so large diff? Sure thats the correct formatting?

I ran npx prisma format

**Comment by nexxeln** [comment]
> > I also have to format. Don't merge before I push that commit.
> 
> Wow why so large diff? Sure thats the correct formatting?

I guess its 2 spaces instead of 4.

**Review by c-ehrlich — APPROVED** [review]
looks good. i don't mind the schema diff, has to be done in some commit sooner or later anyway

**Pull request merged**
