### PR TITLE
docs: minor fixes

### PR DESCRIPTION
**Pull request by AyanavaKarmakar**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

~~- Fix spacing. Looks better now IMO~~
- Consistent use of `JavaScript`

---

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Idk isnt this a bit much? image

**Comment by nexxeln** [comment]
> Idk isnt this a bit much? image

Agree, I liked it how it was tbh

**Comment by asrvd** [comment]
please open an issue first before opening prs which are based on your personal opinion

**Comment by AyanavaKarmakar** [comment]
Got it. Reverted https://github.com/t3-oss/create-t3-app/pull/860/commits/ce5794c97ec5e3607507e1583974cb336aaf3674.

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
