### PR TITLE
docs: upgrade chinese docs

### PR DESCRIPTION
**Pull request by fernandoxu**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by fernandoxu** [comment]
@lodisy need you to review

**Comment by fernandoxu** [comment]
@lodisy I need you to review，bro

**Comment by lodisy** [comment]
> @lodisy I need you to review，bro

Have made comments 4 days ago. Check it out.

**Comment by fernandoxu** [comment]
> > @lodisy I need you to review，bro
> 
> Have made comments 4 days ago. Check it out.
where? 🤯
image

**Comment by lodisy** [comment]
> > @lodisy I need you to review，bro
> 
> Have made comments 4 days ago. Check it out.

The mobile app is unintuitive

**Comment by fernandoxu** [comment]
Ready to merge

**Review by lodisy — APPROVED** [review]

**Review by c-ehrlich — APPROVED** [review]

**Pull request merged**
