### PR TITLE
fix: temp pin next-auth to 4.10 due to peer deps (next)

### PR DESCRIPTION
**Pull request by c-ehrlich**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

temporarily pins next-auth to 4.10
this is because 4.11+ has next 12.2.5 as a peer dep, and we are on 12.3.1

💯

### CODE REVIEW

**Review by nexxeln — APPROVED** [review]

**Comment by juliusmarminge** [comment]
Autorelease doesnt work for next unfortunatly :/

**Comment by nexxeln** [comment]
> Autorelease doesnt work for next unfortunatly :/

:(

**Comment by nexxeln** [comment]
Let's just merge?

**Comment by juliusmarminge** [comment]
> Let's just merge?

Yah or make the change on main too and beta release it real quick

**Comment by c-ehrlich** [comment]
making the change on main is gonna be a bit more work as far as i can tell because it just doesn't have the dependency version map

**Comment by juliusmarminge** [comment]
> making the change on main is gonna be a bit more work as far as i can tell because it just doesn't have the dependency version map

We do it for react-query

**Comment by nexxeln** [comment]
Should I just merge this and @c-ehrlich can make a new one to main?

**Pull request merged**
