### PR TITLE
refactor(cli): add module path aliasing

### LINKED ISSUE #206: Path aliases in `create-t3-app` code
**Is your feature request related to a problem? Please describe.**
We decided that the scaffolded app will not have path aliases here: https://github.com/t3-oss/create-t3-app/issues/85

But it was raised that maybe for the `create-t3-app` code would be worth having a new discussion, as this would only affect contributors and they were not the target of the decisions taken in the original issue.

**Describe the solution you'd like**
Define path aliases in `create-t3-app` so contributors have an easier and consistent way of importing code. In this issue we can propose/discuss what is the path aliases that we want to have, then decide and create a MR from it.

**Describe alternatives you've considered**
Leave imports as they are.

### PR DESCRIPTION
**Pull request by abui-am**
# Add path alias configuration in ts config

- [x] I reviewed linter warnings + errors, resolved formatting, types and other issues related to my work
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

_Summary_
---
close #206 by adding path alias into tsconfig.json

### CODE REVIEW

**Comment by abui-am** [comment]
Would you like me to refactor all of the cli codebase using the module path alias?
I think we better refactor it now or we will ended using them mixed up

**Comment by juliusmarminge** [comment]
> Would you like me to refactor all of the cli codebase using the module path alias?
> 
> I think we better refactor it now or we will ended using them mixed up

Yes please, https://github.com/t3-oss/create-t3-app/issues/206#issuecomment-1193291200

**Comment by abui-am** [comment]
> > Would you like me to refactor all of the cli codebase using the module path alias?
> > I think we better refactor it now or we will ended using them mixed up
> 
> Yes please, [#206 (comment)](https://github.com/t3-oss/create-t3-app/issues/206#issuecomment-1193291200)

done 👍

**Comment by juliusmarminge** [comment]
Looking good! Thanks

**Pull request merged**
