### PR TITLE
chore(docs): migrate docs to astro

### PR DESCRIPTION
**Pull request by nexxeln**
## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

## Changelog

Redid the docs using [Julius's Astro docs template](https://github.com/juliusmarminge/astro-docs).

### CODE REVIEW

**Comment by juliusmarminge** [comment]
You'll have to redeploy this with the correct output folder on Vercel

**Comment by nexxeln** [comment]
Done

**Comment by juliusmarminge** [comment]
> Done

I dont see any content:

image

Tried index, /docs and /docs/introduction

**Comment by nexxeln** [comment]
> > Done
> 
> I dont see any content:
> 
> Tried index, /docs and /docs/introduction
> 
> EDIT: nvm /en/introduction was the link... Should wrap the index.astro in the layout too

Yeah I was thinking we'll have cool looking, more detailed landing page there.

**Comment by juliusmarminge** [comment]
> > > Done
> 
> > 
> 
> > I dont see any content:
> 
> > 
> 
> > Tried index, /docs and /docs/introduction
> 
> > 
> 
> > EDIT: nvm /en/introduction was the link... Should wrap the index.astro in the layout too
> 
> 
> 
> Yeah I was thinking we'll have cool looking, more detailed landing page there.

Yes but i still think having the navigation and searchbar there is good ux

**Comment by nexxeln** [comment]
> > > > Done
> > 
> > 
> > > 
> > 
> > 
> > > I dont see any content:
> > 
> > 
> > > 
> > 
> > 
> > > Tried index, /docs and /docs/introduction
> > 
> > 
> > > 
> > 
> > 
> > > EDIT: nvm /en/introduction was the link... Should wrap the index.astro in the layout too
> > 
> > 
> > Yeah I was thinking we'll have cool looking, more detailed landing page there.
> 
> Yes but i still think having the navigation and searchbar there is good ux

Yeah yeah we can do it later, don't think this needs to blocked for that

**Comment by juliusmarminge** [comment]
Oh right this site isnt published yet. Forgot ;). Then its fine :)

**Comment by juliusmarminge** [comment]
Shiiip it!

**Comment by nexxeln** [comment]
Merge conflicts :(

**Comment by juliusmarminge** [comment]
From what lol?

**Pull request merged**
