### PR TITLE
feat(ci): only run t3-app-matrix is appropriate changes are made

### PR DESCRIPTION
**Pull request by juliusmarminge**
Closes #<issue>

## ✅ Checklist

- [ ] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [ ] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

_[Short description of what has changed]_

cc @c-ehrlich 

---

## Screenshots

_[Screenshots]_

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Related PR #540

**Review by c-ehrlich — COMMENTED** [review]
Looks good :) 

Is the labeller consistently applying the docs label on any change in www now? For example https://github.com/t3-oss/create-t3-app/pull/544 didn't get the label. 

If that works now, maybe add a similar `if` for site/docs-specific actions and I'll close my PR.

**Comment by juliusmarminge** [comment]
> Looks good :)
> 
> Is the labeller consistently applying the docs label on any change in www now? For example #544 didn't get the label.
> 
> If that works now, maybe add a similar `if` for site/docs-specific actions and I'll close my PR.

The Astro build and check is like 20 sec so it's not really an issue if it runs "unnecessarily". If we were to conditionally run that, we'd have to remove that job from the branch-protection and I'm not sure I want to do that.

**Review by c-ehrlich — APPROVED** [review]
Looks great and will save people a bunch of time staring at CI when they make docs contributions :)

**Pull request merged**
