### PR TITLE
feat: add gitpod support

### LINKED ISSUE #472: feat: Gitpod support
### Is your feature request related to a problem? Please describe.

Getting started with contributing to this repository could be made a lot easier.

### Describe the solution you'd like to see

Every one of my contributions so far has been made using an ephemeral development environment using [Gitpod](https://www.gitpod.io/docs/getting-started). Gitpod allows you to create a development environment with the click of a button. You can develop right from your browser or connect to it remotely using the Gitpod VSCode extension.

Although it is already possible to develop using Gitpod (by visiting https://www.gitpod.io/#https://github.com/t3-oss/create-t3-app), adding a config file would significantly improve this workflow because necessary extensions will already be installed automatically.

### Desribe alternate solutions

If possible, I would also like to include [prebuilds](https://www.gitpod.io/docs/prebuilds). If enabled, the Gitpod bot will add a comment to every PR with a link to create a dev environment similar to how the Vercel bot does it. This will make it easier to work with multiple PRs because instead of manually checking a PR out and initializing the project, Gitpod will already do that.

### Additional information

How it looks like for me when developing using Gitpod:
Bildschirm­foto 2022-09-18 um 14 52 14

The PR to add Gitpod support is #471

### PR DESCRIPTION
**Pull request by Coyenn**
Closes #472 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Added .gitpod.yml

### CODE REVIEW

**Review by nexxeln — COMMENTED** [review]
Why do we need this?

**Comment by Coyenn** [comment]
> Why do we need this?

As I said in the corresponding isse: "Getting started with contributing to this repository could be made a lot easier."
So this is not a **must** have but rather an improvement to the contribution workflow for people (like me) who use Gitpod.

**Comment by nexxeln** [comment]
Sorry I missed the issue. Man I really don't like gitpod lol. I will leave this to the other maintainers

**Comment by Coyenn** [comment]
> Sorry I missed the issue. Man I really don't like gitpod lol. I will leave this to the other maintainers

Hahaha no problem. It's not that big of a deal, really.

**Comment by juliusmarminge** [comment]
> Sorry I missed the issue. Man I really don't like gitpod lol. I will leave this to the other maintainers

Me neither

**Comment by nexxeln** [comment]
We'll merge it why not

**Comment by Coyenn** [comment]
> We'll merge it why not

Great! Makes things a lot easier for Gitpod users.

**Pull request merged**
