### PR TITLE
docs: README Revamp

### PR DESCRIPTION
**Pull request by ajcwebdev**
# README Revamp

- [x] I reviewed linter warnings + errors, resolved formatting, types and other issues related to my work
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

Added some information throughout that was missing, reformatted some of the layouts that were a bit wonky, and streamlined the language for clarity and readability.

---

## Screenshots

Theo's face

💯

### CODE REVIEW

**Comment by nexxeln** [comment]
Will let @TheoBr review this since he wrote most of the readme.

**Comment by TheoBr** [comment]
Overall good but a few small things I'd like changed:

- I think it's important to have a "how to use command" as high up as possible. Down to add just the `npx create-t3-app` example near the top? (Maybe with a footnote linking to the "getting started" w/ the other options)
- I really hate combining multiple "commands" into one code block, because you can't use the "copy" button and get what you need. Would prefer to break up the npm, yarn and pnpm options, even if it's a bit bigger :(
- The two pictures near the top feels weird, might be worth moving the T3 logo OVER create-t3-app title to split them apart a bit

Other things I had thoughts on:
- Not sure how I feel about the use of bullet points for visual emphasis on the first section
- Also felt weird having bullet points broken out in _only part 2_ of the T3 Axioms 🤔

**Comment by ajcwebdev** [comment]
Cool, I can make those changes. And with the bullet points it was mostly just trying to get something that visually looked a little cleaner without having much control over actual GitHub markdown styling, so I'll flatten those out.

**Comment by ajcwebdev** [comment]
Edits are all done, I'd `@` you but that's literally rule number 1.

**Comment by nexxeln** [comment]
Looks like we also have merge conflicts, please resolve them.

**Comment by ajcwebdev** [comment]
@nexxeln Done

**Comment by TheoBr** [comment]
Looks great! Might swap out the sub-sub-title with the `npx create-t3-app` to use a codeblock instead so it's insta-copy-able (doesn't need to block this tho)

**Pull request merged**
