### PR TITLE
fix: astro build

### LINKED ISSUE #371: bug: look into resolving react versions
### Provide environment information

```
npx envinfo --system --binaries

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 156.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
```

### Describe the bug

When running `pnpm install`, we fail on invalid peer dependencies and when running `npm ls react` we get this:

CleanShot 2022-08-29 at 17 00 17@2x

Then, when running a build, we see a bunch of errors about breaking the rules of react, which must be cause of this? I can't find other issues that would cause this?

CleanShot 2022-08-29 at 17 04 40@2x

### To reproduce

Clone and install deps, then run a build

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by c-ehrlich**
Closes #371

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Changes components that were arrow functions to named functions
- This fixes the build (edit: on my machine), see: https://github.com/withastro/astro/issues/4220
- Let me know if you want me to rename the files to match the new component names (named function components need to start with uppercase letters)

---

## Screenshots

image

💯

### CODE REVIEW

**Comment by c-ehrlich** [comment]
www builds without errors on my machine with these changes, but seems to still fail on vercel. could someone with vercel access tell me the error log is?

**Comment by nexxeln** [comment]
> www builds without errors on my machine with these changes, but seems to still fail on vercel. could someone with vercel access tell me what the error log is?
> 
> edit: am now getting this error:
> 
> ```
> @ct3a/www:build: [error]  /src/components/AvatarList.astro 
> @ct3a/www:build:     Request to fetch commits failed. Reason: Forbidden
> @ct3a/www:build:        Message: API rate limit exceeded for <MY IP ADDRESS>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
> @ct3a/www:build:   └─ /en/why/index.html (+196ms)
> ```
> 
> have we hit some kind of limit on the GitHub API?

Maybe it'll fix itself after sometime

**Comment by nexxeln** [comment]
> Let me know if you want me to rename the files to match the new component names (named function components need to start with uppercase letters)

I would like that

**Comment by juliusmarminge** [comment]
I think I fixed the deployment on Vercel. Playing around with Turbo remote cache

**Comment by juliusmarminge** [comment]
I am also editing some linting stuff so I can remove the camelCase rule for the www project 👍🏼

**Comment by c-ehrlich** [comment]
> ` [04d247f](/t3-oss/create-t3-app/pull/372/commits/04d247f2350f0ab99168e8dafb80b19deaf90a95)`

let me know if the commit i just made #04d247f is a problem in this regard and i'll revert

**Comment by juliusmarminge** [comment]
> > ` [04d247f](/t3-oss/create-t3-app/pull/372/commits/04d247f2350f0ab99168e8dafb80b19deaf90a95)`
> 
> 
> 
> let me know if the commit i just made #04d247f is a problem in this regard and i'll revert

Nah I can fix it on my end. Thanks for resolving this :)

**Pull request merged**
