### PR TITLE
docs: accessibility improvements

### LINKED ISSUE #881: docs: accessibility improvements
### Is your feature request related to a problem? Please describe.

Ben Myers streamed on twitch recently and had a [fantastic section](https://www.twitch.tv/videos/1627977114)(vod link) going over the docs and accessibility concerns with them. I think this would be a good first issue as well, with most being fairly straight forward updates.

### Describe the solution you'd like to see

These are the concerns raised, with the timestamp from the vod above. Ben goes into really great detail on why each thing is a concern, either to keyboard users, or screen-readers. The topic of contrast was also raised but not covered in detail.

- [x] Focus outline styling needed on T3 logo in navbar (2:00)
- [x] Use outline instead of border for focusable elements to avoid layout shift (3:42, again 54:28)
- [x] Remove tabIndex=“-1” from Twitter links to make them focusable (6:40)
- [x] Focus outline styling needed on on vercel badge (10:35)
- [ ] Nested `main` elements semantically incorrect (possibly due to Astro layouts) (15:15)
- [x] Remove alt text on and replace with empty string (alt=“”) on background image SVG to remove from SR (16:24)
- [x] Update aria-label to reflect relevant unique names of tweet cards (22:10)
- [x] Search bar SR simplify aria-label (24:41)
- [x] U Update full clickable cards to include pseudo element with before: to prevent entire content from being read with SR (explained 26:58, tailwind example shown at 47:52)
- [ ] Wrap CLI in a figure element to make it skippable and prevent ASCII art from being read by SR (if this doesn’t work, role=“region” on CLI) (40:52)
- [ ] aria-hidden on library card logos as the names are right next to them, prevents double name reading on SR (46:14)
- [ ] Theme toggle invisible class prevents being focusable (ref: [https://www.scottohara.me/blog/2017/04/14/inclusively-hidden.html ](https://www.scottohara.me/blog/2017/04/14/inclusively-hidden.html)) - possibly should just be buttons (49:20)
- [ ] Remove double link on videos in docs, possibly pseudo element as well (55:20)
- [ ] Focus styling on GitHub contributors (55:45)
- [ ] aria-labels on theme toggle images (56:45)
- [ ] aria-current for docs navbar (57:38)
- [ ] Video links to have better alt text to indicate what the link does rather than what the image is - possibly video embed (58:30)

### Describe alternate solutions

No alternate solution, amazing accessibility feedback that should be implemented. 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ronanru**
Closes(partially) #881

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Focused elements use outline, instead of border, to remove layout shift
- Outline is visible on all focused elements
- Removed unnecessary duplicate <main> element from the landing page
- Tweet carousel is now accessible with keyboard navigation 
- Improvements for Screen Readers 

check #881 for the full list 

💯

### CODE REVIEW

**Comment by c-ehrlich** [comment]
Tabbing works great for me in Chrome in Safari but skips a bunch of things in Firefox. Can anyone reproduce this?

**Comment by ronanru** [comment]
> Tabbing works great for me in Chrome in Safari but skips a bunch of things in Firefox. Can anyone reproduce this?
Everything works fine on Firefox for me.

**Comment by juliusmarminge** [comment]
https://share.cleanshot.com/jOD89P

firefox buggy for me too

**Comment by ronanru** [comment]
> https://share.cleanshot.com/jOD89P
> 
> firefox buggy for me too

I tested the Vercel preview on the latest Firefox version on multiple different devices, and it works as expected for me. Maybe it's a bug specific to the macOS version of Firefox. I don't own any Apple hardware, so I can't check this. 

I will revert my changes to the tweets slider and technology cards. Hopefully this will fix it, so you can merge this PR.

**Review by juliusmarminge — APPROVED** [review]
seems to work on most setups which is better than what we have today

if someone wants to pick it up and fix the last pieces they can do so later 👍🏼

**Pull request merged**
