### PR TITLE
fix: remove commit hint when no git repo was initialized

### PR DESCRIPTION
**Pull request by Mvmo**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

I've passed the noGit Option to the logNextSteps function and depending on that either logged the 'git commit -m "initial commit"' message or not

---

## Screenshots
With git repo

Without git repo

💯

### CODE REVIEW

**Comment by Mvmo** [comment]
Had some problems with my local dev setup, didn't receive linting errors 😅 
Now everything should be according to the style guidelines

**Comment by juliusmarminge** [comment]
This is fixing a similar thing as #1507 but will conflict quite a bit. 

Will merge 1 and then the other will have to resolve some stuff

**Review by juliusmarminge — APPROVED** [review]
Conflicts

**Comment by juliusmarminge** [comment]
Actually don't think we need this after #1507 that prompts you to initialze a git repo if you aren't in one already.

**Pull request closed without merging**
