### PR TITLE
fix: docs scrollbar behavior

### PR DESCRIPTION
**Pull request by c-ehrlich**
Closes https://github.com/t3-oss/create-t3-app/issues/525

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- fixes the behavior of the docs table of contents scrollbar
- big prettier diff on `globals.css` but the only actual change in that file is in .t3-scrollbar

💯

### CODE REVIEW

**Review by nexxeln — COMMENTED** [review]
gif of messed up custom scrollbar

looks like our custom scrollbar got messed up.

**Comment by c-ehrlich** [comment]
> looks like our custom scrollbar got messed up.

serves me right for only testing on macos. should be ok now

**Review by nexxeln — COMMENTED** [review]
Yup its working, but noticed another thing. Don't know if this is that big of a deal but when I scroll at the extreme left end its scrolling page not the sidebar.

demo gif of weird scrolling

**Review by nexxeln — APPROVED** [review]
Awesome

**Pull request merged**
