### PR TITLE
refactor(www#879): no underline on breadcrumbs

### PR DESCRIPTION
**Pull request by asrvd**
was missing in #879

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

removes text decoration from breadcrumbs on hover.

---

## Screenshots

💯

### CODE REVIEW

**Comment by asrvd** [comment]
@juliusmarminge can be merged

**Comment by c-ehrlich** [comment]
image
I'm still getting the underline

**Comment by asrvd** [comment]
> image
> I'm still getting the underline

on hover?

**Comment by asrvd** [comment]
> > image
> > I'm still getting the underline
> 
> on hover? , but theres no breadcrumb in the ss

**Review by juliusmarminge — APPROVED** [review]

**Comment by c-ehrlich** [comment]
> > image
> > I'm still getting the underline
> 
> on hover? wheres the breadcrumb though?

never mind brain wasnt working -_-

**Pull request merged**
