### PR TITLE
feat: styling on index.tsx without tailwind

### LINKED ISSUE #380: feat: index.tsx styling on template without tailwind
### Is your feature request related to a problem? Please describe.

Index.tsx looks ugly when Tailwind isn't selected and it's not immediately clear that the list elements link to the docs.

### Describe the solution you'd like to see

Give the tailwind-less index.tsx some styling, to look the same or similar as the one with Tailwind. My suggestion would be to use an `index.module.css` file.

### Desribe alternate solutions

- Some other styling method
  - Putting it in `globals.css`
  - Creating some non-module css file
  - Inline styles
  - etc.
- Leaving it as is

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by c-ehrlich**
Closes #380

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-08-15).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] I performed a functional test on my final commit

---

## Changelog

- Add styling to index.tsx files without tailwind using CSS moduls
- Standardize TechnologyCard component
- Add AuthShowcase from `with-auth-trpc.tsx` to `with-auth-trpc-tw.tsx` as well
- Update CLI to install the CSS module when tailwind is not selected

---

## Screenshots

Screenshot 2022-09-01 at 23 16 26

Screenshot 2022-09-01 at 22 34 52

Screenshot 2022-09-01 at 22 37 21

Screenshot 2022-09-01 at 23 15 02

💯

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Duplicate of #386

**Comment by juliusmarminge** [comment]
You guys can battle it out on which CSS is better I guess ;)

I do think an entire installer for this is a bit overkill.

I proposed in #386 (which included the `index.module.css` by default, to remove the file in the tailwindInstaller. What do you think about that?

**Comment by c-ehrlich** [comment]
> I proposed in #386 (which included the `index.module.css` by default, to remove the file in the tailwindInstaller. What do you think about that?

Yea sounds good. I won't touch this PR for a few days, feel free to merge the other one and close this when the installer stuff gets added :)

**Comment by juliusmarminge** [comment]
> > I proposed in #386 (which included the `index.module.css` by default, to remove the file in the tailwindInstaller. What do you think about that?
> 
> 
> 
> Yea sounds good. I won't touch this PR for a few days, feel free to merge the other one and close this when the installer stuff gets added :)

I was actually about to propose closing the other, this one is more complete and fixes some other niceties as well, but I guess we can fix those later

**Comment by juliusmarminge** [comment]
> I think @c-ehrlich did a much better job than i did, i vote to merge this one

Sorry for the inconvenience on your first contribution @frederick-gomez, I hope it doesn't scare you away from contributing again in the future ⭐️

@c-ehrlich are you able to fix the installer stuff or should I merge and make the final adjustments?

**Comment by frederick-gomez** [comment]
No worries, i'll try to help whenever i can

**Comment by c-ehrlich** [comment]
> @c-ehrlich are you able to fix the installer stuff or should I merge and make the final adjustments?

either one is fine, ill probably have time for it tomorrow

**Review by juliusmarminge — APPROVED** [review]

**Pull request merged**
