### PR TITLE
docs: translating docs into russian lang

### PR DESCRIPTION
**Pull request by Yevhenii-Bakhmat**
Closes #<issue>

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/t3-oss/create-t3-app/blob/main/CONTRIBUTING.md) (updated 2022-10-06).
- [x] The PR title follows the convention we established [conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I performed a functional test on my final commit

---

## Changelog

* docs: translated deployment/docker.md into russian
* docs: translated deployment/vercel.md into russian
* docs: translated installation.md into russian

---

## Screenshots

Installation.md
deployment/Vercel.md

💯

### CODE REVIEW

**Comment by nexxeln** [comment]
This is great thanks for doing this!

**Comment by c-ehrlich** [comment]
This is awesome, I'm excited about having docs available in more languages.

Since this is the first translation, I think there are a few things we need to figure out, that are not really related to this specific pr:
1. how to review translations - none of the code owners speak Russian (or most other languages!), but I think it's important that at least one other person reads/reviews any changes to docs.
2. how to deal with translations possibly being out of date in the future - for example we could build a feature that if the English version gets updated, the page of the translated version shows an alert that says "this is x days older than the newest English version"

**Comment by TheoBr** [comment]
Really pumped to see these efforts as well!!! +1 to all of @c-ehrlich's comments.

Also think it's _probably_ worth holding off until we're closer to finalizing the docs so we can have a happier update flow :)

**Comment by Yevhenii-Bakhmat** [comment]
Yeah, Theo's got the point. Though I feel like it will be easier as the quantity of text to translate will be smaller

**Comment by AmadeusTwi** [comment]
I might as well take a look at translations, having Russian as native language and English on pretty high level. Pretty excited to see community is growing.

**Comment by Yevhenii-Bakhmat** [comment]
With this whole next 13 thing i think we need to wait with translation

**Comment by c-ehrlich** [comment]
@Yevhenii-Bakhmat now that we have "officially" launched the docs, I think now is a good time to get started on translation :)

**Comment by Yevhenii-Bakhmat** [comment]
Yep on it.

**Comment by Yevhenii-Bakhmat** [comment]
Ok ill close this PR and open another one coz i might get lost in whole git tree of what's translated and what's not.

**Comment by AmadeusTwi** [comment]
@Yevhenii-Bakhmat check your e-mail mentioned in yours GitHub profile. Thanks in advance!

**Pull request closed without merging**
